define([],
    function () {
        return {
            Refresh: '刷新',
            buttonOK: "确定",
            buttonCancel: "取消",
            buttonPrev: "上一步",
            buttonNext: "下一步",
            buttonBack: "返回",
            buttonContinue: "继续",
            buttonSave: "保存",
            buttonSaveAndNext: "保存并下一步",
            buttonClose: "关闭",
            buttonMore: '更多',
            buttonEdit: "修改",
            buttonDelete: "删除",
            buttonSubmit: "提交",
            buttonPurchaseTransferOrder: "转订单",
            buttonClear: "清空",
            buttonQuery: "查询",
            buttonAdd: "添加",
            buttonCreate: "创建",
            buttonCreateMo: "创建提报周期",
            buttonAddZCD: "添加装车单",
            buttonDone: "完成",
            buttonUpload: "上传",
            buttonPrint: "打印",
            buttonAddAttachment: "添加附件",
            buttonUndetermined: '待定',
            buttonAdopt: '通过',
            buttonReturn: '退回',
            buttonBatchReturn: '批量退回',
            buttonNew: '新建',
            butConfirmDebit: '确认扣款',
            butFullDeduction: '全部扣款',
            butReceiveButton: '确认领取',
            butConfirmReturn: '确认还料',
            buttonConfirm: '确认',
            buttonReject: '驳回',
            buttonSubmitSap: '上报Sap',
            buttonPrevPage: "上一页",
            buttonNextPage: "下一页",
            buttonModify: "修改",
            buttonReaded: '我已阅读',
            buttonNoNeed: "不需要",
            buttonAgree: "同意",
            buttonRefuse: "拒绝",
            buttonBatchRefuse: "批量拒绝",
            buttonExit: "退出",
            buttonGoHome: "返回主页",
            buttonCorrelate: "关联",
            buttonReply: '批复',

            BtnClose: "关闭",
            LastStep: "上一步",

            buttonExport: "导出",
            buttonExportDetail: "导出明细",
            buttonImport: "导入",
            buttonDownLoadTemplate: "下载模板",
            btnReceiveToSrm: '上报SRM',

            InputResult: "录入结果",
            StopTask: '停止',
            StartTask: '启动',
            CountARNotificationSheet: '根据差异生成新的盘点单',
            NotificationLock: '锁库',
            ViewAnalysisReport: "查看分析报告",
            CheckStart: "盘点开始",
            CheckEnd: "盘点结束",
            buttonReset: '重置',
            buttonApproval: '审批',
            buttonPurchase: '生成采购订单',
            buttonTransferOrder: '生成转储订单',

            butonGenerateReceiveManual: '手工添加入库单',

            buttonTrayPart: "组托",
            buttonToRepackageZone: "移至翻包区",
            buttonRepackageBegin: "进行翻包",
            buttonRepackageDone: "翻包任务完成",
            InputLoss: '录入差异原因',
            NewPackageApplyTrans: '重新生成包材申领单',
            buttonPrinted: '打印',
            buttonView: '查看',

            SubmitGFO: "提报GFO",
            SubmitSplit: "创建产能拆分",
            ForecastAdjustment: "预测调整",
            PlanningAdjustment: "计划调整",

            ReceiveConfirm: '确认预收货',
            ConfirmReceive: '确认收货',
            ReceiveDone: '收货完成',
            ReleaseTray: '释放托',
            AllotIn: '调拨入库',
            CreateSheet: '创建单据',
            ProfitPartSearch: '多余零件登记记录查询',

            buttonPrinted: '打印',
            buttonToexamine: '审核',
            butReport: '上报GFO',

            butallReport: '全部上报GFO',

            buttonShelveStart: '开始上架',
            buttonShelveDone: '上架完成',

            buttonTransferStart: '开始移库',
            buttonTransferDone: '移库完成',

            buttonTransfer: '确定移库',
            buttonDetermineRepair: '确定返修',
            buttonDetermineReturnFactory: '确定返厂',
            buttonAutomaticMatching: '自动配车',
            buttonManualMatching: '手动拣配',
            butonGeneratePOOrder: '生成采购订单',

            buttonSaveAndNextOne: '保存并下一个',
            buttonNextOne: '下一个',
            buttonStockUnHold: '解冻',

            butGenerateDeliveryOrder: '生成交货单',

            verifyApprove: '审核通过',

            buttonGroupEdit: '群组维护',
            buttonNotificationResult: '开始盘点',
            buttonAnalysis: '差异分析',
            buttonGoBack: '返回',
            PartSaleTypeName: '新增零件分类',
            ConvertSO: '手工转SO',

            /**********采购管理--开始**********/
            buttonFinanziariaApproval: '财务审核',
            buttonFinanziariaRefuse: '财务驳回',
            buttonInnerApproval: '内部审核',
            /**********采购管理--结束**********/

            /**********售后索赔--开始**********/
            PrintPayDetail: '打印清单明细',
            buttonSaveAndSubmit: '保存并提交',
            buttonCreateCurrentMonth: '生成当月',
            buttonCleanCurrentMonth: '清除当月',
            buttonBatchApproval: '批量审批',
            buttonPrintPayOrder: "打印付款申请单",
            /***2017-05-19***/
            buttonClmPrintLabel: '打印标签',
            buttonClmReturnPart: '返件',
            buttonPDFPrint: 'PDF打印',
            buttonClmSelect: '选择',
            buttonAddPart: '添加零件',
            buttonImportList: '导入清单',
            buttonHistory: "历史",
            buttonAllCreatePay: "全部生成付款清单",
            buttonPartCreatePay: "部分生成付款清单",
            /***保修审计***/
            buttonCreateAuditPlan: '创建审计计划',
            buttonAddDealer: '添加经销商',
            buttonCreateDisplacedPartAudit: '创建旧件审计',
            AddFilter: '添加筛选',
            AddSpecialAttentionFilter: '添加特殊关注筛选',
            /**********售后索赔--结束**********/
            SelectHasContractPart: '选择已有协议零件',
            SelectReadyShipBox: '选择待发运箱子',
            SelectPackingCode: '选择装车单',

            buttonCreatePlan: '生成采购计划',
            butallToexamine: "全部审核",
            butReserve: "预留",
            butCancelReserve: "取消预留",
            buttonBrowserFiles: "选择文件...",
            ChineseLabel: '中文',
            EnglishLabel: '英文',
            buttonAddCYD: '添加承运单',
            Carry: '搬运完成',
            BindTray: '绑定',
            SearchTransDetail: '查看交易明细',

            /**保修索赔返件开始**/
            buttonDealerReturnConfig: '经销商返件配置',
            buttonGenerateBatch: '生成批次',
            buttonDeleteBatch: '删除批次',
            buttionPacking: '装箱',
            buttionCancelPacking: '取消装箱',
            buttionPrintCartonNo: '箱号打印',
            buttonCreateScrapOrder: '创建销毁单',
            buttonCreatePartReturnNotify: '新建零件返回通知',
            buttonScrapApproval: '批准',
            buttonSelect: '选择',
            buttonCreateOutboundOrder: '创建出库单',
            buttonENotify: '保存并通知紧急',
            buttonNNotify: '保存并通知普通',
            InternalAudit: '内部审核',
            SapAudit: '财务审核',
            buttonGreenPathAudit: '绿色通道订单审核',
            buttonInStore: '入库',
            ConfirmInStore: '确认入库',
            buttonOutStock: '出库',
            buttonAjustStock: '库存调整',
            buttonOrderDetail: '订单详情',
            buttonSetNonPrint: "设置不打印",
            buttonSetPrint: "设置打印",
            GreenPathOrderAudit: '绿色通道订单审核',
            ManualSend: '手工分货',
            buttonAddLabor: '添加工时',
            buttonAddOther: '添加其他',
            AgencyOrder: '代下订单',
            CustomOrderAudit: '定制订单审核',
            buttonIssued: '发布',
            buttonUnlock: '解锁',
            buttonAltering: '待修改',
            buttonChecking: '审核中',
            buttonResidentManagement: '驻场代表管理',
            buttonPointsSet: '给分设置',
            buttonSetComplished: '置为已完成',
            buttonSetUnComplished: '置为未完成',
            buttonDisable: '停用',
            buttonCancelComplish: '取消发布',
            buttonAddPlan: '新增计划',
            buttonCalendar: '日历',
            buttonJourney: '查看日程',
            buttonViewChange: '修改前后对比',
            buttonImportPlanTask: '导入任务',
            buttonAddPlanTask: '新增任务',
            buttonInformDealer: '通知经销商',
            buttonSetNotReturn: '设置不返件',
            buttonChangeCampaign: '变更服务活动',
            buttonChangeDealer: '变更经销商',
            buttonSetCompleted: '设为已完成',
            buttonSetUnCompleted: '设为未完成',
            buttonAttachmentAndRemark: '附件和备注',
            /**保修索赔返件结束**/


            /**********库存**********/
            butConfirmFreeze: '确认冻结',
            butConfirmThaw: '确认解冻',
            btnOutLoc: '退台',
            /**********库存**********/

            /**********批售下单、销售预测 tjh**********/
            buttonCreateAdvanceOrder: '生成销售预测',
            buttonCreateBatchOrder: '生成批售订单',
            buttonUpdate: '发布新版本',
            buttonAddCustomPickCard: '新增定制订单拣配卡',
            buttonConfirmDeliver: '确认发货',
            buttonPredictionData: "下发",
            buttonPickUpPart: '取货',
            buttonExcDebit: '异常扣款',
            ReSendApi: '接口重发',
            /**********保修审计，预算监控--开始**********/
            buttonAddFilter: '添加筛选',
            buttonEditFilter: '编辑筛选',
            buttonViewFilter: '查看筛选',
            buttonInspectConfig: '检查项配置',
            buttonDeductionConfig: '扣款项配置',
            buttonAudit: '审计',
            buttonAuditInfo: '审计信息',
            buttonAuditDeleteImage: '删除图片',
            buttonAuditDeleteProject: '删除问题',
            /**********保修审计，预算监控--结束**********/
            buttonScrap: '销毁',
            buttonCarrierPrint: '运单打印',
            buttonSetSupplier: '设置供应商',
            buttonDebit: '扣款',
            buttonDebitOrder: '生成扣款单',
            OrderSwitch: '订单阀门',
            buttonSwitchOn: '开启转换',
            buttonSwitchOff: '关闭转换',
            buttonInvalid: '失效',
            buttonStop: '终止',
            buttonMinus: '减少',
            buttonAjustRecord: '调整记录',
        };
    });