define([],
    function () {
        return {
            Refresh: 'Refresh',
            buttonOK: "Confirm",
            buttonCancel: "Cancel",
            buttonPrev: "Previous step",
            buttonNext: "Next step",
            buttonBack: "Back",
            buttonContinue: "Continue",
            buttonSave: "Save",
            buttonSaveAndNext: "Save and Next step",
            buttonClose: "Close",
            buttonMore: 'More',
            buttonEdit: "Edit",
            buttonDelete: "Delete",
            buttonSubmit: "Submit",
            buttonPurchaseTransferOrder: "Transfer Order",
            buttonClear: "Clear",
            buttonQuery: "Query",
            buttonAdd: "Add",
            buttonCreate: "Create",
            buttonAddZCD: "Add Loading order",
            buttonDone: "Done",
            buttonUpload: "Upload",
            buttonPrint: "Print",
            buttonAddAttachment: "Add Attachment",
            buttonUndetermined: 'Pending',
            buttonAdopt: 'Accept',
            buttonReturn: 'Return',
            buttonBatchReturn: 'Batch returns',
            buttonNew: 'New',
            butConfirmDebit: 'Confirm Debit',
            butFullDeduction: 'Full Deduction',

            buttonConfirm: 'OK',
            buttonReject: 'Reject',
            buttonSubmitSap: 'Submit Sap',
            buttonPrevPage: "Previous Page",
            buttonNextPage: "Next Page",
            buttonModify: "Modify",
            buttonReaded: 'I have read',
            buttonNoNeed: "No Need",
            buttonAgree: "Agree",
            buttonRefuse: "Reject",
            buttonBatchRefuse: "Batch Reject",
            buttonExit: "Exit",
            buttonGoHome: "Go Home",
            buttonCorrelate: "Correlate",
            buttonReply: 'Reply',

            BtnClose: "Close",
            LastStep: "Previous step",

            buttonExport: "Export",
            buttonImport: "Import",
            buttonDownLoadTemplate: "DownLoad Template",

            InputResult: "Input Result",

            StopTask: 'Stop',
            StartTask: 'Start',
            NotificationLock: 'Lock',
            ViewAnalysisReport: "View Analysis Report",
            CheckStart: "Check Start",
            CheckEnd: "Check End",
            buttonReset: 'Reset',

            buttonApproval: 'Approve',
            buttonPurchase: 'Generate Purchase',

            buttonTransferOrder: 'Generate Transfer Order',

            butonGenerateReceiveManual: 'Generate Receive Manual',

            buttonTrayPart: "Tray Part",
            buttonToRepackageZone: "To Repackage Zone",
            buttonRepackageBegin: "Repackage Begin",
            buttonRepackageDone: "Repackage Done",
            InputLoss: 'Input Loss',
            NewPackageApplyTrans: 'New Package Apply Trans',
            buttonPrinted: 'Print',
            buttonView: 'View',

            SubmitGFO: "Submit GFO",
            ForecastAdjustment: "Forecast Adjustment",

            PlanningAdjustment: "Planning Adjustment",

            ReceiveConfirm: 'Receive Confirm',
            ConfirmReceive: 'Confirm Receive',
            ReceiveDone: 'Receive Done',
            ReleaseTray: 'Release Tray',
            AllotIn: 'Allot In',
            CreateSheet: 'Create Sheet',

            buttonPrinted: 'Print',
            buttonToexamine: 'Toexamine',
            butReport: 'Submit GFO',

            butallReport: 'All reported GFO',

            buttonShelveStart: 'Shelve Start',
            buttonShelveDone: 'Shelve Done',

            buttonTransferStart: 'Transfer Start',
            buttonTransferDone: 'Transfer Done',

            buttonTransfer: 'Transfer',
            buttonDetermineRepair: 'Determine Repair',
            buttonDetermineReturnFactory: 'Determine Return Factory',
            buttonAutomaticMatching: 'Auto Matching',
            buttonManualMatching: 'Manual Matching',
            butonGeneratePOOrder: 'Generate PO Order',


            buttonSaveAndNextOne: 'Save And Next',
            buttonNextOne: 'Next',
            buttonStockUnHold: 'UnStock',

            butGenerateDeliveryOrder: 'Generate Delivery Order',


            verifyApprove: 'verify Approve',

            buttonGroupEdit: 'Group Edit',
            buttonNotificationResult: 'Notification Result',
            buttonAnalysis: 'Diff Analysis',
            buttonGoBack: 'Go Back',
            PartSaleTypeName: 'New part type',
            ConvertSO: 'Manual transfer SO',

            /**********采购管理--开始**********/
            buttonFinanziariaApproval: 'Finanziaria Approve',
            buttonInnerApproval: 'Inner Approve',
            /**********采购管理--结束**********/

            /**********售后索赔--开始**********/
            PrintPayDetail: 'Print Details',
            buttonSaveAndSubmit: 'Save & Submit',
            buttonCreateCurrentMonth: 'Generate the month',
            buttonCleanCurrentMonth: 'Clean the month',
            buttonBatchApproval: 'Check',
            buttonPrintPayOrder: "Print PDF",
            /***2017-05-19***/
            buttonClmPrintLabel: 'Print label',
            buttonClmReturnPart: 'Parts return',
            buttonPDFPrint: 'PDF print',
            buttonClmSelect: 'Select',
            buttonAddPart: 'Add',
            buttonImportList: 'Import list',
            buttonHistory: "History",
            buttonAllCreatePay: " Generate All ",
            buttonPartCreatePay: " Generate Portion ",
            /***保修审计***/
            buttonCreateAuditPlan: 'Create Audit Plan',
            buttonAddDealer: 'Add Dealer',

            buttonCreateDisplacedPartAudit: 'Create Displaced Parts Audit',
            buttonCreateAuditPlan: 'Create an Audit plan',



            AddFilter: 'Add filter',
            AddSpecialAttentionFilter: 'Add special attention filter',
            /**********售后索赔--结束**********/
            SelectHasContractPart: 'Select Has Contract Part',
            SelectReadyShipBox: 'Select Ready Ship Box',
            SelectPackingCode: 'Select single loading ',

            buttonCreatePlan: 'Create purchasing plan',
            butallToexamine: "All Toexamine",
            butReserve: "Reserve",
            butCancelReserve: "Cancel Reserve",
            buttonBrowserFiles: "Browser...",
            ChineseLabel: 'Chinese',
            EnglishLabel: 'English',
            buttonAddCYD: 'Add a shipping order ',
            Carry: 'Complete handling ',
            BindTray: 'Bind',


            buttonDealerReturnConfig: 'Dealer Return Setting',
            buttonGenerateBatch: 'Generate Batch',
            buttonDeleteBatch: 'Delete',
            buttionPacking: 'Pack',
            buttionCancelPacking: 'Cancel Pack',
            buttionPrintCartonNo: 'Print Carton No.',
            buttonCreateScrapOrder: 'Create Scraping Order',
            buttonCreatePartReturnNotify: 'Create Part Return Notification',
            buttonScrapApproval: 'Approve',
            buttonSelect: 'Select',
            buttonCreateOutboundOrder: 'Create a delivery order',
            buttonENotify: 'E-Notify',
            buttonNNotify: 'N-Notify',
            InternalAudit: 'Internal Audit',
            SapAudit: 'Financial Audit ',
            buttonGreenPathAudit: 'Green Path Audit',
            buttonInStore: 'In Store',
            ConfirmInStore: 'Confirm InStore',
            buttonOutStock: 'Out Stock',
            buttonAjustStock: 'Ajust Stock',
            buttonOrderDetail: 'Order Detail',
            buttonSetNonPrint: "Set NonPrint",
            buttonSetPrint: "Set Print",
            GreenPathOrderAudit: 'Green Path Audit',
            ManualSend: 'Manual Send',
            buttonAddLabor: 'Add Labor',
            buttonAddOther: 'Add Other',
            AgencyOrder: 'Agency Order',
            CustomOrderAudit: 'Custom Order Audit',
            buttonIssued: 'Release',
            buttonUnlock: 'Unlock',
            buttonAltering: 'To be modified',
            buttonChecking: 'Under Review',
            buttonResidentManagement: 'Resident Management',
            buttonPointsSet: 'Points Set',
            buttonSetComplished: 'Set Complished',
            buttonSetUnComplished: 'Set UnComplished',
            buttonDisable: 'Disable',
            buttonCancelComplish: 'Cancel Complish',
            buttonAddPlan: 'Add Plan',
            buttonCalendar: 'Calendar',
            buttonJourney: 'View Journey',
            buttonViewChange: 'Modify contrast',
            buttonImportPlanTask: 'Import Task',
            buttonAddPlanTask: 'Add Task',
            buttonInformDealer: 'Inform Dealer',
            buttonSetNotReturn: 'Set Not Return',
            buttonChangeCampaign: 'Change Campaign',
            buttonChangeDealer: 'Change Dealer',
            buttonSetCompleted: 'Set Completed',
            buttonSetUnCompleted: 'Set Uncompleted',
            buttonAttachmentAndRemark: 'Attachment And Remark',
            /**********批售下单、销售预测 tjh**********/
            buttonCreateAdvanceOrder: 'Generate sales forecast',
            buttonCreateBatchOrder: 'Generate a wholesale order',
            buttonUpdate: 'Release New Version',
            buttonConfirmDeliver: 'Confirm Deliver',
            buttonExcDebit: 'Debit',
            buttonScrap: 'Scrap',
            buttonAllCreatePay: 'Generate All',
            buttonPartCreatePay: 'Generate Portion',
            buttonCarrierPrint: 'Print Waybill',
            buttonSetSupplier: 'Set Supplier',
            buttonDebit: 'Debit',
            buttonDebitOrder:'GenerateDebitOrder',
            buttonInvalid: 'Invalid',

        };
    });
