define([],
    function () {
        return {

            PleaseFillActualQuantity: 'Please fill in the actual number',

            Confirm: 'Confirm',
            AbnormalDebit: 'exception charge',
            ConfirmDelete: 'Confirm delete ',
            ConfirmDone: 'Confirm done',
            ConfirmStart: "Confirm start",
            ConfirmEnd: "Confirm end",
            ConfirmSave: "Confirm save",
            ConfirmSubmit: "Confirm submit",
            ConfirmTransferOrder: "Confirm transfer order",
            ConfirmAudit: 'Confirm audit',
            ConfirmReject: 'Confirm reject',
            ConfirmSubmitSap: 'Confirm submit sap',
            This: 'This',
            For: ' for',
            DeMa: ' record？',
            BarDeMa: 'Bar info? ',
            NotInput: 'Not input',
            NotFound: 'Not found',
            WrongFormat: 'Wrong format',
            PleaseCheck: 'Please check',
            WrongNum: 'Wrong num',
            NotFoundInWeek: 'No corresponding morning or afternoon items were found during the supply period ',
            quitDialogMessage: "Are you sure you want to close the current dialog box?",
            confirmationTitle: "Please confirm ",
            agreementLoadFail: "Protocol loading failed ...",
            alertTitle: "alert",
            waiteMessage: "In data processing, please wait a moment ... ...",
            Saved: "Save successfully ",
            ResetDone: 'Reset',
            AlreadyOamPrinter: 'Print information has been maintained',

            PleaseSelect: "Please select",
            PSelectCompany: 'Please select company',
            PSelectDloc: 'Please select the turn over table',
            PSelectWm: 'Please select warehouse',
            PSelectZone: 'Please select storage',
            PSelectDlocs: 'Please select library',
            PSelectTime: 'Please select date',
            ManySeparatedWithComma: 'Please separate them in English commas',
            TransferErr: 'Some parts of the document have been operated up and down',
            PSelectDepartment: 'Please enter the department',
            PSelectCostCenter: 'Please enter the cost center',
            PSelectPublishKeeper: 'Please enter the applicant',
            ManySeparatedWithComma: "multiple please use comma separated",
            TransferErr: 'part of the document has been carried out on the lower part of the operation',
            LossDone: 'The document has been completed, do not repeat the operation',

            from: "from",
            to: "to",
            down: 'down',
            TransferSucceeded: 'Transfer Succeeded',
            OperationSucceeded: 'Operation Succeeded',
            Completed: 'Completed',
            CreateNotificationDone: 'inventory sheet creates success',
            ImportErrMeun: 'cannot import empty files',
            MaterialCodeBelongPartOnly: 'rack coding has been maintained under other material frames',
            ImportErrMissColumn: 'missing column name in the uploaded Excel form ',
            ImportErrIndex: 'no.',
            ImportErrField: 'line',
            ImportErrFieldMsg: 'field information is wrong',
            ImportNullFieldMsg: 'field information cannot be empty',
            ImportNullOrErrorFieldMsg: 'field information cannot be empty or is not specified format',
            MaterialCodeOnly: 'the frame code repeats, please confirm only',
            ImportfieldErrA: 'already exists in the system, please confirm',
            ImportfieldErrB: 'does not exist in the system, please confirm that',
            ImportfieldErrD: 'the input format is wrong. Please confirm',
            ImportErrFile: 'please select the Excel file for import',
            OverLength: 'is too long (restricted to 20 bits)',
            OverLengthB: 'is too long (restricted to 30 bits)',
            PChoosePartForNotification: 'please select the parts to be checked in, add inventory, release',
            ImportErrNum: 'can only enter positive integers, decimals',
            ExportNoData: 'query to at least one data for export ',
            PrintNoData: 'please query to print at least one data',
            DeliveryOrderData: 'please select at least one data to generate the delivery order',
            TransferOrderData: ' select at least one of the data to generate the dump order',
            OperateDataFail: 'operation failed. Please try again.',
            PCheckMainData: 'please check master data',
            POamPackage: 'please maintain the package master data',
            HoldDloca: 'the library of the next shelf is frozen',
            HoldDlocb: 'the library on the shelf is frozen',
            TransferPlace: 'Please create the transit area in the system and perform the shelf operation ',
            PictureType: 'You can only upload pictures in.Jpg,.Png,.Gif format ',
            //wxm
            PartGroupProfitErr: 'no purchase agreement cannot be priced',
            HasOnProgressPart: 'already exists information being processed, and new versions cannot be added before the financial review passes',
            PartGroupProfitExit: 'this client group has adopted margin management',
            PartGroupModulusExit: 'this customer group has adopted discount factor management',
            PartGroupRateErr: "not getting markup rates can't be priced",
            PartErr: 'does not exist in the system, please confirm that',
            PartGroupErr: "not getting to the price group can't be priced",
            MdmPartGroupErr: "no price groups found in master data can't be priced.",
            ComplaintsReason: 'cause of complaint',
            LineNum: 'line',
            Invalid: 'invalid',
            Middle: 'medium',
            HasInputInventoryDetail: 'already entered inventory details',
            HasNoWarehouseCanRead: 'you have no access to any warehouse. If necessary, please ask the administrator for it. ',
            InputInteger: 'can only enter positive integers',
            AddDetailErr: 'details already exist and cannot be added repeatedly',
            SubmitDetailErr: 'please create document details submitted for inventory adjustment',
            SubmitDetailSN: 'please create document details submitted',
            ActFinished: 'confirmed',
            ActDone: 'has been completed',
            LowRequireNum: 'cannot be greater than the quantity required',
            PackageNeedOamWm: "please maintain the package area, warehouse position, and then receive the warehouse.",
            PackageNeedOamWmB: 'please maintain the outsourcing area, the warehouse location, and then receive delivery warehousing',
            PackageNeedOamWmC: 'please maintain the package area, warehouse location',
            PackageNeedOamWmD: 'please maintain the location, location, location',
            PackageNeedOamWmE: 'please maintain the green channel shelves, library location',
            PackageNeedOamWmF: 'Please keep a good margin, location',
            LossNumLowStocks: 'The number of losses must be less than the current stock',

            Day: 'day',
            LagerThan: 'greater than',
            Equal: 'is equal to',
            AddNoStockMsg: 'in the system there is no check to the parts inventory information, not loss',
            AddNoStockSN: "cannot query inventory information in the system without querying the package",
            PleaseInput: 'please enter',
            PInputReceiveNum: 'Please enter the quantity of goods received ',

            LowTrayNum: 'support group must be equal to the part in the actual number of dhone',
            NumMustLow: 'the quantity entered cannot be greater than the actual quantity',
            ReceivableNumLowRequire: 'receivable amount cannot be greater than quantity of demand',
            NotificationNotDone: 'All parts in the inventory are not finished',
            NoResultFind: 'did not find the zone data in the system',
            Total: "altogether.",
            Bar: "strip",
            Record: " records",
            NotSameWareHouse: "please note that the warehouse No. VIN you fill in is not in accordance with the warehouse designated by the inventory sheet.!!!",
            ThisVINHasNoCarInfo: "excuse me, you filled out the VIN number and no vehicle information was found....",
            WrongStoreLocationWithSelected: "please note that when the library is out of order, please fill in the correct library location.",
            UnderStock: 'insufficient stock',
            ArtHasThisPart: 'the process has been associated with the part',
            ReleaseTrayErr: 'is not a part of release',
            MessageToGFO: 's record to GFO? ',
            NoAppMsg: 'Please add application form for submission',
            ConfirmTransferStart: 'confirm began to move',
            ConfirmTransferDone: 'confirm transfer',
            NotificationNoData: 'please prepare the parts data to be checked and take stock',
            NotificationAddRepeat: 'this part has been added to the inventory request form, please confirm',
            ChooseTheSameWmNo: 'original warehouse and destination warehouse cannot be the same',
            AsnRepeat: 'ASN odd numbers already exist',
            UnShelvePlease: ' please complete the shelf first',
            UnReadySheet: 'documents not complete all transfer operation, please check',
            RepackageDlocNeeded: 'please select a flip pad',
            NoRepackageTask: 'did not specify a package search task',
            PInputPart: 'please enter part number',
            ShelveNoRepeat: 'document details already have this rack coded',
            ConfirmStockUnhold: 'confirm thaw selected record',
            ConfirmVerify: 'confirm audit',
            Warning: 'warning',
            DateStartLagerThanEnd: 'start time must not be less than or equal to the end time',
            NoAppMsgTo: 'please prepare data for submission',
            PartAddRepeat: 'this part has been added to the group and cannot be repeated added',
            GreenPartNotNeed: 'this part does not need to be transported to the green channel area',
            ConfirmSubmitQuota: 'confirm that this information is to be submitted? Note: the status of the supplier has been changed to "be audited" and will need to be re examined before being effective. Please review it in time. ',
            RepeatQuota: 'already exists in the match list. Please do not repeat it. ',
            QuotaOrMinSplitRequired: 'The supplier is required to modify the priority or quotas.',
            SupplierQuotaHasOverdue: 'vendor quota effective time has expired, please delete. ',
            SupplierContractHasOverdue: 'the purchase agreement has expired, please delete. ',
            NoChooseAnySupplier: 'did not select any vendor. ',
            TotalQuotaNot100: "the total sum of the quota is not equal to 100%. Please revise.",
            OnceImportEqualOnePlan: "PS: once imports only generate a plan, if you need to generate more than one plan, import more than once. ",
            /********** claims -- began **********/
            PleaseAddBelow: 'Please append in below "',
            DeRemark: '" Note/Remark：',
            AfterSaveCantEdit: 'Any action is restricted after saving but appending.',
            PleaseAddRemarkBelow: 'Enter note in below:',
            RefustOrReturnAddRemak: 'Enter the reason before return/rejection.',
            PleaseSelectAuthorizationType: 'Please select the type of PA first.',

            New: 'New',
            Edit: 'Edit',
            Reply: 'Approve',
            PayYearMonthToDealer: '{PayYear} {PayMonth} warranty payment list',
            DealersNeedToSettleThisMonth: '{CheckoutCount} Dealers need to be settled in this month.',
            HasAuditDealers: '{HasAuditCount} dealers have been checked.',
            AuditingDealers: '{AuditingCount} dealers are waiting to be checked.',
            WaitingPayToDealer: 'Amount to be paied(without VAT)：￥{WaitPayAmount}',
            TaxPayDealer: 'Tax：￥{TaxPayDealer}',
            TotalPayToDealer: 'Total：￥{WaitPayTotalAmount}',
            ConfirmReceiveWithPayNo: 'The invoice of payment list [{PayNo}] has been received?',
            ConfirmHasPaidWithPayNo: 'Remittance for payment list  [{PayNo}] has been done?',
            ConfirmHasAccountingWithPayNo: 'Payment for Payment list [{PayNo}] has been debitted?',
            InvoiceNoticeDetail: 'In {PayYear } / { PayMonth }, Your company\'s warranty expenses excluding tax is {Amount} RMB and VAT is ￥{TaxTotal}, which is ￥{TotalAmount} in total.Please check and issue the invoice accounding to the following details and then express to our company.',
            InvoiceNoticeDetailDealerRebate: '{Title}, Your company excluding tax is {Amount} RMB and VAT is ￥{TaxTotal}, which is ￥{TotalAmount} in total.Please check and issue the invoice accounding to the following details and then express to our company.',
            InvoiceInformationAndAddress: 'VAT invoice information and mailing address',
            ClmSelect: 'Please select',
            ComfirmDeleteSelectedMutliData: 'Are you sure to delete these [DelNum] selected items?',
            ComfirmReturnSelectedMutliData: 'Are you sure to return these [Num] selected items?',
            ComfirmRefuseSelectedMutliData: 'Are you sure to reject these [Num] selected items?',
            ComfirmAdoptSelectedMutliData: 'Are you sure to accept these [Num] selected items?',
            ComfirmReceiveMutliData: 'Are you sure to receipt these [Num] selected items?',
            ComfirmCheckMutliData: 'Are you sure to pass these [Num] selected items?',
            ComfirmPaidMutliData: 'Are you sure to pay for these [Num] selected items?',
            ComfirmDeleteSelectedSignleData: 'Are you sure to delete the data of claim [[DelNo]]?',
            ComfirmSubmitSelectedSignleData: 'Are you sure to submit the data of claim [[DelNo]]?',
            ComfirmSelectedSignleData: 'Are you sure to confirm the data of claim [[DelNo]]?',
            ComfirmRejectSelectedSignleData: 'Are you sure to refuse the data of claim [[DelNo]]?',
            ComfirmReturnSelectedSignleData: 'Are you sure to return the data of claim [[DelNo]]?',
            ComfirmAdoptSelectedSignleData: 'Are you sure to accept the data of claim [[DelNo]]?',
            ComfirmSaveAndSubmitData: 'Are you sure to save and submit the data of claim [[DelNo]]?',
            PleaseAddFaultPhenomenonFirst: 'Please enter "fault description" in note area first',
            PleaseAddFaultDiagnosisFirst: 'Please enter "fault diagnosis" in note area first',
            PleaseAddRepairProgrammeAndResultFirst: 'Please enter "solution" in note area first',
            PayYearMonthToDealerWithDealerInfo: '{PayMonth}{PayYear}{DealerName}（ Dealer Code：{DealerCode}）Reconciliation list（Unit：RMB）',
            ThisMonthReceivables: 'Receivable account of this month: ￥{WaitPayAmount}',
            VINHasNoRelatedInfo: 'Sorry, no releated information was found about this VIN.',
            VINIllegal: 'Invalid VIN, 17 digit required.',
            ClmHasRepeatDealer: 'Sorry, this dealer has already existed',
            ClmTravelMileageMoreThanTravelMileageEnd: 'Sorry, start mileage must be smaller than the end. ',
            ClmOnlyMainWorkHour: 'It can only have one causal part/causal labor. ',
            ClmHasMainPartButNoSupplier: 'Sorry, no supplier was found for this causal part ({PartNo}) or invalid selection ',
            ClmCantPrintNewWarranty: '[New] status warranty claim can not be printed.',
            ClmCantGetPartPrice: 'No qualified component found. Please check if it\'s priced by corporate finance.',
            ClmHasRepeatWorkHour: 'Error! This labor code has been involed in "labor cost"',
            ClmHasRepeatPart: 'Error! This part has been involed in "materail cost"',
            ClmHasRepeatOther: 'Error! This expense has been involed in "other cost"',
            ClmRepairEndFirst: 'Sorry, please fill "repair end date" first',
            ClmVehicleTypeFirst: 'Sorry, unmatchable vehicle model, labor time is unavailable',
            ClmDealerFirst: 'Sorry, unmatchable dealers, labor time is unavailable',
            ClmConfirmDeleteFromPayItem: 'Sure to delete claim {warrantyNo) from this payment list?',
            ClmWorkCodeNotBeEmpty: 'Labor code can\'t be empty',
            ClmWorkRemarkNotBeEmpty: 'Operation description can\'t be empty',
            ClmWorkHoursNotBeEmpty: 'Labor time can\'t be empty',
            ClmWorkPriceNotBeEmpty: 'Labor rate can\'t be empty',
            ClmRepairItemHasOneNoPrice: 'Sorry, the price of labor/part (code: {Code}, description: {Remark}) involed in this repair package has not been maintained, automatic addition doesn\'t work.',
            ClmChooseRepairPackage: 'Repair package had been selected, are you sure to replace the current labor cost/part cost?',
            ClmIsTrigger3R: 'Trriger or not',
            ClmReturnMustChooseOne: 'Sorry, return action only works on single claim',
            ClmCloseJobGreatThanRepairEnd: 'Sorry, The settlement date must be greater than or equal to repair end date',
            ClmPleaseSelectVINFirst: 'Please select VIN first and then select pre-approval',
            clmPleasePercentTotalNotEqual100: 'The sum of customer, dealer and manufacture percentage is not equal to 100.',
            ClmReplyQuantityMustLessThanOrEqualQuantity: 'Sorry, accepted Qty must be less than or equal to applied Qty.',
            ClmPleaseSelectVINFirst: ' Please select VIN first and then select the pre authorization! ',
            ClmPleaseInputRepairStartFirst: 'Please fill repair start date firt',
            ClmPayToDealerExport: 'Interval Export',
            ClmCreatePaySelected: ' Sure to generate payment list by selected [num] items(Dealers can invoice directly after generation )? ',
            ClmCreatePayAll: ' Sure to generate all unpaied data to payment list (Dealers can invoice directly after generation )? ',
            ClmWrongPage: ' Sorry, the page you entered is wrong. Click OK will automatically jump to the right page. ',
            ClmOnlyCheckOwnerDealerInfo: ' Sorry, you can only check your dealer\'s information. ',
            ClmJobSettingMonth: '每{interval}个月的{Ordinal}日执行一次',
            ClmJobSettingWeek: '每{interval}周的星期{Ordinal}执行一次',
            ClmJobSettingDay: '每{interval}天执行一次',
            ClmIsRefreshVIN: '确定要刷新VIN信息吗？',
            /**********售后索赔--结束**********/
            /**********采购管理--开始**********/
            NotWritePartInfo: 'part information has not been filled yet',
            ConfirmCreatePurchasePlan: 'is it sure that the selected record will generate the purchase plan? ',
            SpmQuotaCountMoreThanContractCount: 'quota quantity is greater than agreement quantity. The excess quantity is {Quantity}',
            SpmContractCountMoreThanQuotaCount: 'the number of agreements is greater than the quota number, and the number of agreements is not equal to 1. The excess quantity is {Quantity}',
            FixQuotaNeedManualDel: 'this error requires manual deletion of the quota! ',
            PartsHasInListPleaseEdit: 'part number: {Parts}, not added. Reason: already exists in the list, you can modify it directly. ',
            PleaseSelectCompanyWarehouseFirst: "please select the company and the warehouse first.! ",
            ErrorTelForamt: 'landline phone format is incorrect',
            ErrorFaxForamt: 'fax format is incorrect',
            BoxHasInListPleaseEdit: 'number: {boxNum}, did not add. Reason: already exists in the list, you can modify it directly. ',
            PackingHasInListPleaseEdit: 'loading No.: {PackingCode}, not added. Reason: already exists in the list, you can modify it directly. ',
            PleaseSelectCompanyWarehouseFirst: "please select the company and the warehouse first.! ",
            OrderHasTransferred: 'purchase order has been generated successfully! ',
            TelOrPhoneOrEmailMustHaveOne: 'phone, mobile and email at least one item! ',
            ConfirmFinanziariaApproval: 'are you sure you want financial review? ',
            /**********采购管理--结束**********/
            ErrorEmailForamt: 'mailbox format is incorrect',
            ErrorMobileForamt: 'phone format is incorrect',
            ChooseOneSN: 'please select at least one',
            PleaseCheckIfHasAgreementOrInBelow: 'warm tip: if no designated supplier is found, please check whether it has not yet signed the purchase agreement or in the assigned supplier. ',
            StartTimeMustLessThanEndTime: 'The start time must not be less than or equal to the end time ',
            HasRepeatSupplierDate: 'the dealer ({SupplierNo}) already has a order calendar, please check it. ',
            HasRepeatWmDate: 'this warehouse ({WmNo}) already has an order processing time. Please check it. ',
            SupplyCycleCantEmpty: 'the supply cycle cannot be empty. ',
            PartHasNoContract: 'part number: {PartNo}, the supplier who has not signed the agreement has not been found and can not complete the save! ',
            PleaseMeasureOnleOneForEdit: 'please make sure that only one line is selected and modified! ',
            PurchasePlanCreateSuccess: 'purchasing plan generated successfully! ',
            OnlyNumberWithDecimalSix: 'You can only enter numbers, and you can count up to 6 decimal places!',
            OnlyNumber: 'You can only enter numbers!',
            OnlyNaturalNumber: 'You can only enter integers greater than 0!',
            CantMinMoreThanMax: 'The minimum amount cannot be greater than the maximum amount！',
            OnlyTwoDecimalsNumber: 'You can enter only numbers, and at most two decimal places！',
            OnlyTwoDecimalsNumberLessThanHundred: 'You can only enter numbers no greater than 100, and at most two decimal places!',
            CantMinMoreThanMax: 'the minimum approval amount shall not be greater than or equal to the maximum amount of approval! ',
            OnlyThreeDecimalsNumber: 'You can enter only numbers, and at most three decimal places！',
            /**********系统文件上传**********/
            UploadFileTitle: 'add system upload file',
            FileListTitle: 'upload file list:',
            FileUploadExcel: ' Please upload.Xlsx or XLS format file ',
            CantStartOrEndWithNotOwnInventory: 'excuse me, the inventory counter is not for you. Please select the stock taking person as your own inventory sheet for the start / end. ',

            //zyc
            VINWarehouseNonExistent: 'VIN encoding does not exist / original library / warehouse does not exist',
            ErrorVINLEN17: 'input error, VIN code length must be 17 bits',
            TransferSuccessNotAllowedUpdate: 'transfer success record is not allowed to modify',
            TransferSuccessNotAllowedDel: 'transfer success record is not allowed to delete',
            TransferID: 'transfer number',
            TransferSuccess: 'transfer success',
            RepairSuccess: 'maintenance success',
            ReturnFactorySuccess: 'return to factory success',
            RepairSuccessNotAllowedUpdate: 'successful repair records are not allowed to modify',
            RepairSuccessNotAllowedDel: 'records of successful repairs are not allowed to be deleted',
            ReturnFactoryNotAllowedUpdate: 'records of successful factory returns are not allowed to be modified',
            ReturnFactoryNotAllowedDel: 'successful factory records are not allowed to be deleted',
            ReturnFactoryNotAllowedFC: 'successful factory return is not allowed to return to factory',
            RejectedNotAllowedUpdate: 'status of order locking, assembly line, vehicle submission and audit can not be modified',
            RejectedNotAllowedDel: 'only the purchase order of the draft / submission status can be deleted',
            StatePurchaseOrdersCanBeRviewed: 'only draft / submit, purchase order status can be audited',
            VINNonExistent: 'VIN code does not exist',
            WhetherToAudit: 'do you want to review?',
            WhetherToDel: 'do you want to delete?',
            DetermineWhetherToGenerateVIN: 'is it OK to generate VIN encoding?',
            RecordsThatHaveBeenGeneratedDoNotAllowBinding: 'generated records are not allowed to bind',
            CanOnlySelectRecordsInTheAudit: 'can only select records in audit',
            TheAuditListCannotBeDeleted: 'audited dumps cannot be deleted',
            WhetherToGenerate: 'do you want to generate?',
            TransferOrderCode: 'dump order',
            RepairID: 'repair odd numbers',
            QuantityDemandDateMustFilledout: 'quantity / requirement date must be filled out',
            TheSelectedRecordPurchaseOrderIsNotAllowedGenerate: 'selected records, purchase orders are empty, not allowed to generate',
            SelectTheRecordsYouWantToGenerate: 'please select the record to be generated',
            RejectedStatus: 'has dismissed',
            ReturnFactoryID: 'return factory odd number',
            //zyc
            TrayNoPart: 'selected is no parts!',
            MoveTo: 'move to',
            NoFreeDloc: 'no free library to move!',
            PChooseOrder: 'please select an order',
            PChooseAllotOrder: 'please select the transfer form.',
            CreateOrder: 'create successful entry number:',
            SureShelveThis: 'confirm shelves to Library',
            PChoosePart: 'please select parts',
            PChooseReason: 'please select reason',
            PChooseNum: 'enter quantity please',
            SubmitSuccess: 'offers success! ',
            PTrayThenReceive: "please proceed with the receipt of the goods.",
            PRThenReceive: "please put in order and then complete the receipt.",
            NoPermissionCount: 'cannot be greater than the actual difference in quantity',
            NoAvailableToTray: "all parts have been assembled and no assembly parts are available.",
            AlreadyOam: 'flip pad has maintained the storage type ',
            DetailNoEdit: 'order detail status has been reviewed. No action',
            AlreadyVerify: 'the information you selected has been approved and cannot be operated',
            PChooseAReason: 'please select a reason',
            NoAvailableDloc: 'there is no suitable library location',
            AllWaitSubmit: 'all pending submission',
            NoWaitSubmit: 'there is no record to be submitted',
            NoRepackageDloc: 'please save the area in the system, the repository location, storage type ',
            ExistCustomerGroupNo: 'has a customer group numbered {GroupNo}',
            NotCancel: 'the information you selected is not cancelled and cannot be approve',
            NotGreenPathOrder: 'the information you selected is not a green channel order and cannot be approve',
            NotGreenPathWait: 'the information you selected is not pending and cannot be approve',
            NotCustomOrder: 'the information you selected is not a custom order and cannot be approved',
            TimeErr: 'date format is wrong',
            NoBox: 'did not select any combination of numbers, please confirm and try again!',
            ConfirmHoldDone: 'confirm freeze',
            ConfirmUnFrozenDone: 'confirm thaw',
            ConfirmDiscardDone: 'confirm scrap',
            PartHasHold: 'parts have been frozen',
            HasDefaultWm: 'the dealer already has a default warehouse, please uncheck the default warehouse',
            HasSameWm: 'the dealer already has a warehouse of the same order type, please re select',
            PChoosePackage: 'please select package',
            PChooseShelve: 'please select the rack',
            PInputShelve: 'please enter the rack code',
            ExportErr: 'export failed',
            RackingQtyClaim: 'the maximum number of shelves must be an integral multiple of the package modulus',
            ExportErr: 'export failed',
            EffectiveDateMustLessThanExpiryDate: 'the start date must not be less than or equal to the deadline.',
            PartForShelveErra: 'is less than the minimum modulus parts packaging, can not generate on the mission',
            PartForShelveErrb: 'is less than the minimum packaging parts modulus, unable to generate tasks shelves',
            NoTimeHasSelected: 'the selected week {week} has no choice in the morning or afternoon session, please check',
            NoWeekHasSelected: 'has selected {week} week {time} time, but did not select week, please check',
            PleaseChooseOneItem: 'please select a data to operate',
            NoInfoReadyToSumit: 'no status for uncommitted data',
            PleaseChooseOneItem: 'Please Choose One Item',
            EffectiveDateMustLessThanExpiryDate: 'Effective Date Must Less Than Expiry Date',
            ConfirmGenerateBatch: 'Confirm Generate Batch',
            BatchHasTransferred: 'Batch Generated Successfully！',
            ConfirmGenerateBatch: 'Are you sure to generate batch',
            NotInternalAudit: 'the selected part [PartNo] is not an internal pending status and is prohibited from auditing.',
            NotInternalAuditRole: 'the selected part [PartNo], the currently logged in user does not have an audit role. No auditing is allowed.',
            NotSapAudit: 'the selected part [PartNo] is not a financial pending status and is prohibited from auditing.',
            BatchHasTransferred: 'Batch has been generated successfully! ',
            BatchGenerateError: 'batch generation failed. Please select the returned type, the demand side, the recipient of the same parts',
            ImportHasRepeatData: 'import data in the same dealer presence of the same warehouse, please check',
            ImportHasDefaultData: 'there are multiple default warehouses in the same imported data, please check',
            ImportHasRepeatDealerData: 'there are multiple identical dealer codes in the imported data',
            WeekHasNoPairData: 'morning or afternoon of the week failed to match the week of the supply cycle',
            NotPartType: 'upload data in the main data part type is not (parts), prohibit uploading',
            BatchGenerateError: 'Batch generation failed. Select parts of the same ReturnType, DemandSide and ReceivingParty',
            ConfirmPacking: 'Confirm Packing',
            ConfirmCancelPacking: 'Confirm Cancel Packing',
            PackingFinished: 'Packing finished',
            CancelPackingFinished: 'Cancel packing finished',
            PackingFailed: 'Packing failed，please choose parts that unpacked',
            CancelPackingFailed: 'Cancel packing failed，please choose parts that packed',
            DeliverInfo: 'Deliver Info',
            ReceiveInfo: 'Receive Info',
            SapStatusWrong: 'The selected parts must all be within the audited state before they can be reported to the SAP ',
            SubmitStatusWrong: 'The selected spare parts must all be submitted to continue submission ',
            InStoreFinished: 'InStore Finished',
            InStoreFailed: 'InStore Failed',
            StoreFailedTags: 'Please choose parts that Received and not in storage',
            PleaseSelectOldPartStock: 'please select old parts inventory',
            NotFoundPriceGroup: 'did not find the completed price group information',
            ConfirmNotify: 'confirm the notification',
            OnlyCanDeleteStatus: 'can only be deleted to be submitted with rejected messages',
            OnlyCanSubmitStatus: 'can only be submitted to be submitted with rejected messages',
            ClmSelfAuthorizationAlert1: "The ratio of the hours to which the manufacturer, distributor, customer and customer must be equal to 100",
            ClmSelfAuthorizationAlert2: "The sum of the parts of the manufacturer, distributor and customer must be equal to 100",
            ClmPayPrintInfo: ' {CheckoutCount} dealers need to settle this month, excluding tax amount {WaitPayAmount} yuan, tax {TaxPayDealer} yuan, a total of {WaitPayTotalAmount} yuan. ',
            OnlyCanSubmitStatus: 'can only be submitted to be submitted with rejected messages',
            PlsSelectDate: 'please fill in the date',
            InputWrongNumber: 'quantity entered error',
            ConfirmInStore: 'confirm warehousing',
            EmptyGroupName: 'customer group did not fill in or fill out incorrectly',
            NullGroup: 'the customer group is not found in the system. Please make sure the name is filled correctly',
            NullData: 'failed to find valid price confirmation data',
            DNPFail: 'actual DNP fill incorrectly',
            MSRPFail: 'actual MSRP fill incorrectly',
            WrongStatus: 'data is not to be submitted status. No import',
            DeleteBatchError: 'Only undelivered batch can be deleted.',
            ConfirmPrint: 'Are you sure to print selected Parts\' tags?',
            ConfirmUnPrint: 'Are you sure to config that selected parts\' tags are not allowed to print?',
            ConfirmSetWaitPrint: 'Are you sure to config that selected parts\' tags are waitting to be printed?',
            ClmSelfAuthorizationAlert1: 'The sum of manufacture, dealer  and customer\'s percentage of labor cost  must be 100%.',
            ClmSelfAuthorizationAlert2: 'The sum of manufacture, dealer  and customer\'s percentage of material cost must be 100%.',
            ComfirmIssuedSelectedSignleData: 'Are you sure to release 【[DelNo]】?',
            ComfirmIssuedSelectedMutliData: 'Are you sure to release selected 【[DelNum]】 records?',
            ComfirmPassSelectedSignleData: 'Are you sure to approve 【[DelNo]】?',
            ComfirmPassSelectedMutliData: 'Are you sure to approve selected 【[DelNum]】 records?',
            RepairPackagesIsRequired: 'Service package is required for campaign',
            HourIsRequired: 'Labor time is required',
            RepairPackageContentNotAllowEmpty: 'Service package of campaign cann\'t be empty',
            SuccessFilterVin: 'Repeat VIN exists and has been filtered',
            VinImportSuccess: 'VIN has been imported successfully',
            MaxAmountCanNotLessThanMinAmount: 'The maxmum amount can\'t be  less than the minimum one.',
            OnlyInZeroAndOne: 'Between 0 and 1.',
            NotZipCode: 'Invalid zip code.',
            NotPhoneNum: 'Invalid telephone number.',
            ReturnDuty: 'Responsibility of parts return.',
            ReceiveRemark: 'Explanations of parts return',
            OnlyAllowDelete: 'Only deletion is allowed.',
            OnlyAllowEdit: 'Only modification is allowed.',
            UnSubmitOrRejectScrap: 'Un-submitted or returned scraping oder.',
            OnlyAuditInAudit: 'Only scraping order at "checking" status can be approved',
            ScrapModelRequired: 'Scraping mode is required',
            ArrivalDateRequired: 'Arriving date is required',
            PartRequired: 'Part is required',
            ConfirmOutbound: 'Are you sure to take it outbound ?',
            CodeExists: 'This code has existed already!',
            PublishedRecallForbidEdit: 'Released service actins are not allowed to be edited.',
            PublishedRecallForbidDelete: 'Released service actins are not allowed to be deleted.',
            CantEditFailedInfo: 'Expired data are not allowed to be edited.',
            ConfirmPublish: 'Are you sure to release?',
            VinImportFail: 'Failed to import VIN',
            PartImportSuccess: 'Success to import parts list',
            PartImportFail: 'Failed to import parts list',
            SuccessFilterPart: 'Repeat part exist and has been filtered',
            ConfirmNewReturnRequest: 'Are you sure to create new parts return requirement?',
            /**保修索赔返件结束**/
            CantBiggerThanUnreceiveQty: 'the order quantity for part number {PartNo} shall not be greater than the quantity not received',
            CantBiigerThanDemandQty: 'the receivable quantity of part number {PartNo} shall not be greater than the quantity required by order',
            CanNotBeZero: 'the quantity receivable and the order quantity of part number {PartNo} should not be 0',
            NoEntrustZoneFound: 'warehouse Defaults are not found outside the default storage area',
            ReceivePartNumHasBiggerThanZero: 'Qty. of received part must be larger than 0',
            AlreadyHasZCD: "the loading list has been selected. Please delete and continue operation.",
            CantAuditBecauseNoNeed: 'audit failed, the host factory does not need to audit non idle parts transfers',
            GreenPathOrderHasAudit: 'green channel orders must be completed before the audit can be converted',
            AddWarrantySuccessed: 'Warranty: {WarrantyNo} added successfully!',
            CantAboveStock: 'conversions cannot be greater than the total amount of inventory',
            CantTransZero: 'conversions are 0, no conversions',
            ClmPayPrintInfo: '{CheckoutCount} dealers need to be settled  in this month.￥{WaitPayAmount } without VAT, VAT￥{TaxPayDealer} Total: ￥{WaitPayTotalAmount}',
            TotalRatesNeOne: '12 months of procurement target allocation, the sum of the total sum must be equal to 1',
            PleaseChooseDealer: 'Please select dealer',
            PublishedClauseForbidDelete: 'Released 3R terms are not allowed to be deleted.',
            ValidityEndMustGreaterThanStart: 'End date must be later than start date',
            ProductionEndMustGreaterThanStart: 'Production end date must be later than production start date',
            ComfirmCancelPublishSelectedSignleData: 'Are you sure to invalidate [[DelNo]] ?',
            ComfirmCancelPublishSelectedMutliData: 'Are you sure to invalidate selected [[DelNum]] ?',
            ComfirmRejectPublishSelectedSignleData: 'Are you sure to return [[DelNo]]? ',
            ComfirmRejectPublishSelectedMutliData: 'Are you sure to return  selected  [[DelNum]] records?',
            NotChooseAnyDealer: 'Dealer is missing',
            NotChooseAnyPart: 'Part is missing',
            TaskTypeAlreadyExisting: 'task type already exists. Please check! ',
            TaskTypeAlreadyExisting: 'task type already exists. Please check! ',
            HaveTaskInThisTaskType: 'there is a task Association beneath this task type. Please delete the associated task first! ',
            WarrantyTotal: 'Warranty claims',

            /**********批售下单、销售预测 tjh**********/
            SubmitSuccess: 'Success to submit!',
            SubmitFailed: 'Failed to submit!',
            QuantityMustBeGreaterThanZero: 'Qty. must be larger than 0.',
            QuantityForecastWeekMustFilledout: 'Quantity and forecast week are required.',
            QuantityWarehouseMustFilledout: 'quantity / warehouse / vehicle use / Type of funds requirement must be filled out!',
            AdditionalSOLimit: 'Quantity Available',

            MainPartIsRequired: 'Please select causal part!',
            MainHourIsRequired: 'Please select causal operation!',
            SettlementMonthError: 'Settlement start date must be earlier than the end date.',
            StockAdjust: 'Adjust stock',
            PleasePackageBefore: 'Please pack and print first',
            VinRequired: 'VIN is required',
            PartRequired: 'Part id required',
            PartOrSupplierAtLeastOne: 'There is at least one component and supplier',
            NotRecallCode: 'The active code format is incorrect',
            ConfirmDeliver: 'Confirm deliver',
            PleaseChoosePackageItem: 'Please choose batch in packaged status',
            ConfirmChange: 'Are you sure to change?',
            NoBasicPriceHasFound: 'The selected part hasn\'t been priced. Please maintain the basic price first.',
            ConfirmReceive: 'Confirm receipt',
            ReceiveComplete: 'Receive complete',
            ConfirmInStore: 'Confirm inStore',
            InStoreComplete: 'InStore complete',
            ReceiveDebitError: 'Only "Status"  is Received and "Receipt status" is not Received or  Pending data can be added abnormal debit.',
            InstoreDebitError: 'The data is at "InStore" and "Received" status are not allowed to abnormal debit.',
            NoPartInfo: 'No queryable part information.',
            ComfirmDebit: 'Are you sure to deduct all relevant cost ?',
            ClmWrongPage: 'Sorry, error page entered, please click confirm button to jump to the correct page automatically. ',
            ClmOnlyCheckOwnerDealerInfo: 'Sorry, you only can check your own dealer\'s information.',
            ClmCreatePaySelected: 'Are you sure to generate the payment list for the selected [num] data (dealer can invoice directly after the generation)? ',
            ClmCreatePayAll: 'Sure to generate all unpaied data to payment list (dealers can invoice directly after generation ) ?',
            FileUploadExcel: 'Only .Xlsx or XLS can be uploaded.',
            ClmChooseSelfScrap: 'Please choose the scraping order in self - scraping mode.',
            ClmCantInvoiceWithPaymentListNoAccepted: 'No invoicing! Payment list hasn\'t been accepted.',
            ClmCantInvoiceWithNoPayment: 'No invoicing! This payment list doesn\'t exist.',
            ChooseDataNoSupplier:'Please select datas unbinding from supplier. '




        };
    });