//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_MOVIE_DISTRICT
    {
        public DF_MOVIE_DISTRICT()
        {
            this.DF_MOVIE_STORE = new HashSet<DF_MOVIE_STORE>();
        }
    
        public int DISTRICTID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<DF_MOVIE_STORE> DF_MOVIE_STORE { get; set; }
    }
}
