//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_MOVIE_EMPLOYEE
    {
        public DF_MOVIE_EMPLOYEE()
        {
            this.DF_MOVIE_STORE1 = new HashSet<DF_MOVIE_STORE>();
            this.DF_MOVIE_EMPLOYEE1 = new HashSet<DF_MOVIE_EMPLOYEE>();
        }
    
        public int EMPID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<int> SUPERVISORID { get; set; }
        public string TITLE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<int> STOREID { get; set; }
    
        public virtual DF_MOVIE_STORE DF_MOVIE_STORE { get; set; }
        public virtual ICollection<DF_MOVIE_STORE> DF_MOVIE_STORE1 { get; set; }
        public virtual ICollection<DF_MOVIE_EMPLOYEE> DF_MOVIE_EMPLOYEE1 { get; set; }
        public virtual DF_MOVIE_EMPLOYEE DF_MOVIE_EMPLOYEE2 { get; set; }
    }
}
