//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_MOVIE_TAPE
    {
        public DF_MOVIE_TAPE()
        {
            this.DF_MOVIE_RENTAL = new HashSet<DF_MOVIE_RENTAL>();
        }
    
        public int TAPEID { get; set; }
        public int MOVIEID { get; set; }
        public int STOREID { get; set; }
        public string AVAILABLE { get; set; }
    
        public virtual DF_MOVIE_MOVIE DF_MOVIE_MOVIE { get; set; }
        public virtual ICollection<DF_MOVIE_RENTAL> DF_MOVIE_RENTAL { get; set; }
    }
}
