//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_ORDERS
    {
        public DF_ORDERS()
        {
            this.DF_ORDERDETAILS = new HashSet<DF_ORDERDETAILS>();
        }
    
        public int CUSTID { get; set; }
        public int ORDERID { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
    
        public virtual DF_CUSTOMERS DF_CUSTOMERS { get; set; }
        public virtual ICollection<DF_ORDERDETAILS> DF_ORDERDETAILS { get; set; }
    }
}
