//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DF_PRODUCTS
    {
        public DF_PRODUCTS()
        {
            this.DF_ORDERDETAILS = new HashSet<DF_ORDERDETAILS>();
        }
    
        public string PRODUCTID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<DF_ORDERDETAILS> DF_ORDERDETAILS { get; set; }
    }
}
