//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REPORTLOG
    {
        public int REPORTDATE { get; set; }
        public string REPORTCODE { get; set; }
        public string IMPORTSTIME { get; set; }
        public string IMPROTETIME { get; set; }
        public string EXPORTSTIME { get; set; }
        public string EXPORTETIME { get; set; }
        public string UPLOADSTIME { get; set; }
        public string UPLOADETIME { get; set; }
        public string STATUS { get; set; }
        public string MSG { get; set; }
        public int UPLOADTIMES { get; set; }
        public string REPORTSEQ { get; set; }
    }
}
