//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DOADATA
    {
        public string PRODUCTCODE { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
        public string MATERIALSN { get; set; }
        public string MATERIALCODE { get; set; }
        public string NEWIMEI { get; set; }
        public string NEWSN { get; set; }
        public string RESN { get; set; }
        public string REPN { get; set; }
        public string CHECKOVER { get; set; }
        public string REDATE { get; set; }
        public string SUPPLIER { get; set; }
        public int IMPORTDATE { get; set; }
        public int IMPORTTIME { get; set; }
    }
}
