//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MATERIAL_BARCODE
    {
        public decimal SERIAL { get; set; }
        public string MACHINE_NO_LC { get; set; }
        public string MACHINE_NO_LI { get; set; }
        public string PACKING_LOT_NO { get; set; }
        public string MACHINE_MODEL_NO { get; set; }
        public string MATERIAL_NO { get; set; }
        public string MATERIAL_CLASS_CODE { get; set; }
        public string BARCODE { get; set; }
        public string PRINTED_DESC { get; set; }
        public short MATERIAL_QTY { get; set; }
        public string PRODUCT_DATE { get; set; }
        public string SCAN_DATE { get; set; }
        public string LUCKY_NO { get; set; }
        public string SALEORDER { get; set; }
        public string SHIP_TO { get; set; }
        public string PO { get; set; }
        public decimal IMPORTDATE { get; set; }
        public decimal IMPORTTIME { get; set; }
    }
}
