//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PAC_MACHINE
    {
        public decimal SERIAL { get; set; }
        public string MO { get; set; }
        public string PRODUCTCODE { get; set; }
        public string PHONEMODEL { get; set; }
        public string SN { get; set; }
        public string NO11S { get; set; }
        public string NETWORKNO { get; set; }
        public string ASN { get; set; }
        public string WORKDATE { get; set; }
        public string SUPPLIER { get; set; }
        public string FACTORY { get; set; }
        public string WORKSHOPTYPE { get; set; }
        public string CHARLINE { get; set; }
        public string SHIFT { get; set; }
        public string COLOR { get; set; }
        public string GROUPSN { get; set; }
        public string BN { get; set; }
        public string PDATE { get; set; }
        public string PTIME { get; set; }
        public string OUTFSN { get; set; }
        public string SHIPPINGMARK { get; set; }
        public string OPERATOR { get; set; }
        public string IMEI1 { get; set; }
        public string IMEI2 { get; set; }
        public string MODATE { get; set; }
        public string MACHINE_NO_LC { get; set; }
        public string MACHINE_NO_LI { get; set; }
        public string PRODUCT_DATE { get; set; }
        public string LUCKY_NUMBER { get; set; }
        public string VF_NAME { get; set; }
        public string YMW { get; set; }
        public string SO { get; set; }
        public string STR_SOFTEDITION { get; set; }
        public string GROUPMO { get; set; }
        public int IMPORTDATE { get; set; }
        public int IMPORTTIME { get; set; }
        public string PSN { get; set; }
    }
}
