//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PACKING_LOT_INFO
    {
        public decimal SERIAL { get; set; }
        public string PACKING_LOT_NO { get; set; }
        public string MATERIAL_NO { get; set; }
        public string MATERIAL_CLASS_CODE { get; set; }
        public int MATERIAL_QTY { get; set; }
        public string REF_TEXT { get; set; }
        public string START_DATE { get; set; }
        public string YMW { get; set; }
        public string VF_NAME { get; set; }
        public int IMPORTDATE { get; set; }
        public int IMPORTTIME { get; set; }
    }
}
