//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PARTSNO
    {
        public decimal SERIAL { get; set; }
        public string PRODUCTCODE { get; set; }
        public string PHONEMODEL { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
        public string ASN { get; set; }
        public string MO { get; set; }
        public string WORKDATE { get; set; }
        public string MATERIALSN { get; set; }
        public string MATERIALCODE { get; set; }
        public string SUPPLIER { get; set; }
        public string FACTORY { get; set; }
        public string GROUPSN { get; set; }
        public Nullable<int> MATERIAL_QTY { get; set; }
        public string MATERIAL_CLASS_CODE { get; set; }
        public int IMPORTDATE { get; set; }
        public int IMPORTTIME { get; set; }
        public string PSN { get; set; }
    }
}
