//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DEFECTIVE
    {
        public decimal SERIAL { get; set; }
        public string WORKSHOPTYPE { get; set; }
        public string CHARLINE { get; set; }
        public string SHIFT { get; set; }
        public string PROCESS { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
        public string PCBCODE { get; set; }
        public string GROUPSN { get; set; }
        public string FAILURECODE { get; set; }
        public string FAILUREPHENOMENON { get; set; }
        public string ISMAINTAIN { get; set; }
        public string WORKDATE { get; set; }
        public int IMPORTDATE { get; set; }
        public int IMPORTTIME { get; set; }
    }
}
