//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLAPTENSTION
    {
        public decimal SERIAL { get; set; }
        public string APID { get; set; }
        public string SSCODE { get; set; }
        public decimal TENSIONA { get; set; }
        public decimal TENSIONB { get; set; }
        public decimal TENSIONC { get; set; }
        public decimal TENSIOND { get; set; }
        public decimal TENSIONE { get; set; }
        public string APTYPE { get; set; }
        public string APAPPERANCE { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string EATTRIBUTE2 { get; set; }
        public string EATTRIBUTE3 { get; set; }
    }
}
