//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLARMORPLATECONTROL
    {
        public string OID { get; set; }
        public string APID { get; set; }
        public string BPCODE { get; set; }
        public string VERSION { get; set; }
        public string THICKNESS { get; set; }
        public int USEDTIMES { get; set; }
        public string STATUS { get; set; }
        public string MANUFACTURERSN { get; set; }
        public int LBRATE { get; set; }
        public decimal TENSIONA { get; set; }
        public decimal TENSIONB { get; set; }
        public decimal TENSIONC { get; set; }
        public decimal TENSIOND { get; set; }
        public decimal TENSIONE { get; set; }
        public string USEDMOCODE { get; set; }
        public string USEDSSCODE { get; set; }
        public string UUSER { get; set; }
        public int UDATE { get; set; }
        public int UTIME { get; set; }
        public int USEDTIMESINMO { get; set; }
        public string RUSER { get; set; }
        public Nullable<int> RDATE { get; set; }
        public Nullable<int> RTIME { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> UNITPRINT { get; set; }
    }
}
