//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLALERTLINEPAUSE
    {
        public string ITEMSEQUENCE { get; set; }
        public string SUBITEMSEQUENCE { get; set; }
        public string SSCODE { get; set; }
        public string OPCODE { get; set; }
        public decimal ALERTVALUE { get; set; }
        public string GENERATENOTICE { get; set; }
        public string SENDMAIL { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
