//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLASNIQC
    {
        public string IQCNO { get; set; }
        public string STNO { get; set; }
        public int STNO_SEQ { get; set; }
        public string STATUS { get; set; }
        public string INVUSER { get; set; }
        public string APPLICANT { get; set; }
        public int APPDATE { get; set; }
        public int APPTIME { get; set; }
        public string LOTNO { get; set; }
        public Nullable<int> INSPDATE { get; set; }
        public Nullable<int> PRODDATE { get; set; }
        public string STANDARD { get; set; }
        public string METHOD { get; set; }
        public string RESULT { get; set; }
        public Nullable<int> RECEIVEDATE { get; set; }
        public string PIC { get; set; }
        public string INSPECTOR { get; set; }
        public string ROHS { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
        public string ATTRIBUTE { get; set; }
        public string STS { get; set; }
        public string PRIORITY { get; set; }
    }
}
