//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLALERTNOTICE
    {
        public decimal SERIAL { get; set; }
        public string ITEMSEQUENCE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SUBITEMSEQUENCE { get; set; }
        public decimal NOTICESERIAL { get; set; }
        public string ALERTTYPE { get; set; }
        public string STATUS { get; set; }
        public string MOLIST { get; set; }
        public string NOTICECONTENT { get; set; }
        public string ANALYSISREASON { get; set; }
        public string DEALMETHODS { get; set; }
        public int NOTICEDATE { get; set; }
        public int NOTICETIME { get; set; }
        public string DEALUSER { get; set; }
        public Nullable<int> DEALDATE { get; set; }
        public Nullable<int> DEALTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
