//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCUSTOMERSEGMENT
    {
        public string IMEI1 { get; set; }
        public string KEY1 { get; set; }
        public string KEY2 { get; set; }
        public string KEY3 { get; set; }
        public string KEY4 { get; set; }
        public string KEY5 { get; set; }
        public string MD5 { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public Nullable<int> CDATE { get; set; }
        public Nullable<int> CTIME { get; set; }
        public string KEY6 { get; set; }
        public string KEY7 { get; set; }
        public string KEY8 { get; set; }
        public string KEY9 { get; set; }
        public string DEVICETYPE { get; set; }
        public string SEGMENTTYPE { get; set; }
        public string FLAG { get; set; }
        public string SN1 { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> SEGMENTID { get; set; }
    }
}
