//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARTONINFO
    {
        public string PKCARTONID { get; set; }
        public string CARTONNO { get; set; }
        public short CAPACITY { get; set; }
        public short COLLECTED { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public decimal WEIGHT { get; set; }
        public decimal WEIGHTMIN { get; set; }
        public decimal WEIGHTMAX { get; set; }
        public string ISSHIPPED { get; set; }
        public string VICECARTONNO { get; set; }
        public Nullable<short> VICECAPACITY { get; set; }
        public string WEIGHTCONFIRMUSER { get; set; }
    }
}
