//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARTONRECHECK
    {
        public decimal SERIAL { get; set; }
        public decimal SEQ { get; set; }
        public string CARTONNO { get; set; }
        public string RCARD { get; set; }
        public string QCRESULT { get; set; }
        public string QCUSER { get; set; }
        public Nullable<int> QCDATE { get; set; }
        public Nullable<int> QCTIME { get; set; }
        public string PKSTATUS { get; set; }
        public string PKUSER { get; set; }
        public Nullable<int> PKDATE { get; set; }
        public Nullable<int> PKTIME { get; set; }
    }
}
