//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDOWN
    {
        public string DOWNCODE { get; set; }
        public string RCARD { get; set; }
        public string MOCODE { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string SSCODE { get; set; }
        public string RESCODE { get; set; }
        public string DOWNSTATUS { get; set; }
        public string DOWNREASON { get; set; }
        public int DOWNDATE { get; set; }
        public int DOWNSHIFTDATE { get; set; }
        public int DOWNTIME { get; set; }
        public string DOWNBY { get; set; }
        public string UPREASON { get; set; }
        public Nullable<int> UPDAY { get; set; }
        public Nullable<int> UPTIME { get; set; }
        public string UPBY { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public int ORGID { get; set; }
    }
}
