//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDOC
    {
        public decimal DOCSERIAL { get; set; }
        public decimal DIRSERIAL { get; set; }
        public string DOCNAME { get; set; }
        public string DOCNUM { get; set; }
        public string DOCVER { get; set; }
        public string DOCCHGNUM { get; set; }
        public string DOCCHGFILE { get; set; }
        public string ITEMLIST { get; set; }
        public string OPLIST { get; set; }
        public string MEMO { get; set; }
        public string KEYWORD { get; set; }
        public string CHECKEDSTATUS { get; set; }
        public string VALIDSTATUS { get; set; }
        public string DOCTYPE { get; set; }
        public string UPUSER { get; set; }
        public int UPFILEDATE { get; set; }
        public string SERVERFILENAME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
