//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDN
    {
        public string DNNO { get; set; }
        public string SHIPTOPARTY { get; set; }
        public string DNLINE { get; set; }
        public string ITEMCODE { get; set; }
        public string ITEMDESC { get; set; }
        public int ORGID { get; set; }
        public string FRMSTORAGE { get; set; }
        public long DNQUANTITY { get; set; }
        public Nullable<long> REALQUANTITY { get; set; }
        public string UNIT { get; set; }
        public string MOVEMENTTYPE { get; set; }
        public string MOCODE { get; set; }
        public string ORDERNO { get; set; }
        public string CUSORDERNO { get; set; }
        public string CUSORDERNOTYPE { get; set; }
        public string TOSTORAGE { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string DNFROM { get; set; }
        public string DNSTATUS { get; set; }
        public string RELATEDDOCUMENT { get; set; }
        public string BUSINESSCODE { get; set; }
        public string DEPT { get; set; }
        public string MEMO { get; set; }
        public string REWORKMOCODE { get; set; }
        public string SAPSTORAGE { get; set; }
        public string FLAG { get; set; }
        public string TRANSACTIONCODE { get; set; }
        public Nullable<decimal> CUSORDERLINE { get; set; }
        public string SHIPTOCOMPANY { get; set; }
    }
}
