//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEXCEPTIONCODE
    {
        public string EXCEPTIONCODE { get; set; }
        public string EXCEPTIONNAME { get; set; }
        public string EXCEPTIONDESC { get; set; }
        public string EXCEPTIONTYPE { get; set; }
        public string EXCEPTIONFLAG { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
