//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEQPTSLOG
    {
        public decimal SERIAL { get; set; }
        public string EQPID { get; set; }
        public string FINDUSER { get; set; }
        public int FINDMDATE { get; set; }
        public int FINDMTIME { get; set; }
        public string TSINFO { get; set; }
        public string REASON { get; set; }
        public string SOLUTION { get; set; }
        public string RESULT { get; set; }
        public string TSTYPE { get; set; }
        public string STATUS { get; set; }
        public int DURATION { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
