//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLESOPPICS
    {
        public string SERIAL { get; set; }
        public string ITEMCODE { get; set; }
        public string OPCODE { get; set; }
        public string PICFULLNAME { get; set; }
        public int PICSEQ { get; set; }
        public string PICTITLE { get; set; }
        public string PICMEMO { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string PICTYPE { get; set; }
    }
}
