//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEQUIPMENT
    {
        public string EQPID { get; set; }
        public string EQPNAME { get; set; }
        public string EQPDESC { get; set; }
        public string MODEL { get; set; }
        public string TYPE { get; set; }
        public string EQPTYPE { get; set; }
        public string EQPCOMPANY { get; set; }
        public string CONTACT { get; set; }
        public string TELPHONE { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string EATTRIBUTE2 { get; set; }
        public string EATTRIBUTE3 { get; set; }
        public string EQPSTATUS { get; set; }
        public string MUSER { get; set; }
        public decimal MDATE { get; set; }
        public decimal MTIME { get; set; }
    }
}
