//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLERPINVINTERFACE
    {
        public string RECNO { get; set; }
        public string MOCODE { get; set; }
        public string STATUS { get; set; }
        public string SRNO { get; set; }
        public string ITEMCODE { get; set; }
        public int QTY { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public Nullable<int> UPLOADDATE { get; set; }
        public Nullable<int> UPLOADTIME { get; set; }
        public string UPLOADUSER { get; set; }
        public string LINKSRNO { get; set; }
        public string EATTIBUTE1 { get; set; }
    }
}
