//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFROZEN
    {
        public string RCARD { get; set; }
        public string LOTNO { get; set; }
        public int LOTSEQ { get; set; }
        public string MOCODE { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public int FROZENSEQ { get; set; }
        public string FROZENSTATUS { get; set; }
        public string FROZENREASON { get; set; }
        public Nullable<int> FROZENDATE { get; set; }
        public Nullable<int> FROZENTIME { get; set; }
        public string FROZENBY { get; set; }
        public string UNFROZENREASON { get; set; }
        public Nullable<int> UNFROZENDATE { get; set; }
        public Nullable<int> UNFROZENTIME { get; set; }
        public string UNFROZENBY { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
