//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFACERLOG
    {
        public decimal SERIAL { get; set; }
        public string FACERCODE { get; set; }
        public string FACERSPECCODE { get; set; }
        public Nullable<decimal> MAXCOUNT { get; set; }
        public Nullable<decimal> USEDCOUNT { get; set; }
        public Nullable<decimal> ALERTCOUNT { get; set; }
        public Nullable<decimal> TOTALCOUNT { get; set; }
        public string STATUS { get; set; }
        public string RESCODE { get; set; }
        public string MOCODE { get; set; }
        public string SSCODE { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> USERDATE { get; set; }
        public Nullable<int> USERTIME { get; set; }
        public string UUSER { get; set; }
    }
}
