//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINVRECEIPTDETAIL
    {
        public string RECEIPTNO { get; set; }
        public int RECEIPTLINE { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<int> ORDERLINE { get; set; }
        public string RECSTATUS { get; set; }
        public string IQCSTATUS { get; set; }
        public string MEMO { get; set; }
        public string ITEMCODE { get; set; }
        public int PLANQTY { get; set; }
        public Nullable<int> QUALIFYQTY { get; set; }
        public Nullable<int> ACTQTY { get; set; }
        public Nullable<int> RECDATE { get; set; }
        public Nullable<int> RECTIME { get; set; }
        public string RECUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
        public string VENDERLOTNO { get; set; }
        public string MOCODE { get; set; }
        public string INVUSER { get; set; }
        public string ISINSTORAGE { get; set; }
    }
}
