//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLITEM
    {
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMDESC { get; set; }
        public string ITEMUOM { get; set; }
        public string ITEMVER { get; set; }
        public string ITEMTYPE { get; set; }
        public string ITEMCONTROL { get; set; }
        public string ITEMUSER { get; set; }
        public int ITEMDATE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string ITEMCONFIG { get; set; }
        public string ITEMCARTONQTY { get; set; }
        public Nullable<int> ITEMBURNINQTY { get; set; }
        public Nullable<decimal> ELECTRICCURRENTMINVALUE { get; set; }
        public Nullable<decimal> ELECTRICCURRENTMAXVALUE { get; set; }
        public Nullable<int> SHIPBOXCAPACITY { get; set; }
        public string PKRULECODE { get; set; }
        public int ORGID { get; set; }
        public string CHKITEMOP { get; set; }
        public Nullable<int> LOTSIZE { get; set; }
        public string PRODUCTCODE { get; set; }
        public string NEEDCHKCARTON { get; set; }
        public string NEEDCHKACCESSORY { get; set; }
        public int PCBACOUNT { get; set; }
        public decimal CARTONWEIGHT { get; set; }
        public string CKCARTONWEIGHT { get; set; }
        public decimal CARTONWEIGHTMIN { get; set; }
        public decimal CARTONWEIGHTMAX { get; set; }
        public string CKPSNWEIGHT { get; set; }
        public decimal PSNWEIGHTMIN { get; set; }
        public decimal PSNWEIGHTMAX { get; set; }
        public string MIXCARTONRULE { get; set; }
        public string LOTNORULE { get; set; }
        public string ISCHECK { get; set; }
        public Nullable<decimal> CHECKRATE { get; set; }
        public Nullable<int> ITEMVICECARTONQTY { get; set; }
        public string ISFAI { get; set; }
        public string ISTSFORCELOT { get; set; }
        public int CARTONIMEICHECKQTY { get; set; }
        public string LABELCHECKVALUE { get; set; }
        public string COLORCAP { get; set; }
        public string ISPREPROCESS { get; set; }
        public Nullable<int> WEIGHINGNUM { get; set; }
        public Nullable<decimal> WEIGHINGRANGE { get; set; }
        public string COLORBOTTOM { get; set; }
        public Nullable<decimal> PALLETCAPACITY { get; set; }
        public Nullable<decimal> SAMPLINGPROPORTION { get; set; }
        public Nullable<int> OQCCHECKTIMES { get; set; }
    }
}
