//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLIQCDETAIL
    {
        public string IQCNO { get; set; }
        public string STNO { get; set; }
        public int STLINE { get; set; }
        public string ITEMCODE { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<decimal> ORDERLINE { get; set; }
        public string STDSTATUS { get; set; }
        public Nullable<decimal> RECEIVEQTY { get; set; }
        public string CHECKSTATUS { get; set; }
        public string UNIT { get; set; }
        public string MEMO { get; set; }
        public string MEMOEX { get; set; }
        public Nullable<decimal> SAMPLEQTY { get; set; }
        public Nullable<decimal> NGQTY { get; set; }
        public string PIC { get; set; }
        public string ACTION { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
        public string ATTRIBUTE { get; set; }
        public string TYPE { get; set; }
        public int ORGID { get; set; }
        public string STORAGEID { get; set; }
        public string CONCESSIONSTATUS { get; set; }
        public Nullable<decimal> CONCESSIONQTY { get; set; }
        public string CONCESSIONNO { get; set; }
        public string SRMERRORMSG { get; set; }
        public string DINSPECTOR { get; set; }
        public Nullable<int> DINSPDATE { get; set; }
        public Nullable<int> DINSPTIME { get; set; }
        public string PURCHASEMEMO { get; set; }
        public string INSTYPE { get; set; }
        public string CONCESSIONMEMO { get; set; }
        public string BADGRADE { get; set; }
        public string VENDORLOTNO { get; set; }
        public string VENDORDATECODE { get; set; }
        public string ESD { get; set; }
        public string MSL { get; set; }
    }
}
