//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLITEM2CUSTOMER
    {
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string ITEMDESC { get; set; }
        public string CUSTOMERITEMCODE { get; set; }
        public string CUSTOMERPRODUCTMODEL { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MODELCODE { get; set; }
        public string CUSTOMER { get; set; }
        public string CUSTOMERMODEL { get; set; }
        public string CUSTOMERMODELCODE { get; set; }
        public string COLOUR { get; set; }
        public string PRINTCOLOUR { get; set; }
        public string MAT_PROJECT { get; set; }
    }
}
