//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINVTRANSFER
    {
        public string TRANSFERNO { get; set; }
        public string FRMSTORAGEID { get; set; }
        public string TOSTORAGEID { get; set; }
        public string TRANSFERSTATUS { get; set; }
        public string RECTYPE { get; set; }
        public string MEMO { get; set; }
        public Nullable<int> CREATEDATE { get; set; }
        public Nullable<int> CREATETIME { get; set; }
        public string CREATEUSER { get; set; }
        public int ORGID { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
    }
}
