//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLITEMLOTDETAIL
    {
        public string SERIALNO { get; set; }
        public string LOTNO { get; set; }
        public string MCODE { get; set; }
        public string STORAGEID { get; set; }
        public string STACKCODE { get; set; }
        public string SERIALSTATUS { get; set; }
        public int PRINTTIMES { get; set; }
        public string LASTPRINTUSER { get; set; }
        public int LASTPRINTDATE { get; set; }
        public int LASTPRINTTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
