//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINSTORAGEINFO
    {
        public string RCARD { get; set; }
        public string MOCODE { get; set; }
        public string IMEI { get; set; }
        public string SN { get; set; }
        public string TSN { get; set; }
        public string MAC { get; set; }
        public string BT { get; set; }
        public string CARTONCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string CODE1 { get; set; }
        public string CODE2 { get; set; }
        public string CODE3 { get; set; }
        public string IMEI2 { get; set; }
        public string MEID { get; set; }
        public string PSN { get; set; }
        public string NETCODE { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string ID3 { get; set; }
        public string ID4 { get; set; }
        public string ID5 { get; set; }
        public string STATUS { get; set; }
        public string DATACABLE { get; set; }
        public string BATTERY { get; set; }
        public string CHARGER { get; set; }
        public string SUBCAMERA { get; set; }
        public string REARCAMERA { get; set; }
        public string TWOINONE { get; set; }
        public string THREEINONE { get; set; }
        public string PCBA { get; set; }
        public string TP { get; set; }
        public string PHONE { get; set; }
        public string HEADSET { get; set; }
        public string LCD { get; set; }
        public string EATTRIBUTE2 { get; set; }
        public string EATTRIBUTE3 { get; set; }
        public string EATTRIBUTE4 { get; set; }
        public string EATTRIBUTE5 { get; set; }
        public string EATTRIBUTE6 { get; set; }
        public string EATTRIBUTE7 { get; set; }
        public string EATTRIBUTE8 { get; set; }
        public string EATTRIBUTE9 { get; set; }
        public string EATTRIBUTE10 { get; set; }
    }
}
