//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINVTRANSFERDETAIL
    {
        public string TRANSFERNO { get; set; }
        public int TRANSFERLINE { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<int> ORDERLINE { get; set; }
        public string TRANSFERSTATUS { get; set; }
        public string MEMO { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public int PLANQTY { get; set; }
        public Nullable<int> ACTQTY { get; set; }
        public string CUSTOMERCODE { get; set; }
        public string CUSTOMERNAME { get; set; }
        public Nullable<int> TRANSFERDATE { get; set; }
        public Nullable<int> TRANSFERTIME { get; set; }
        public string TRANSFERUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
    }
}
