//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLITEMLOT
    {
        public string LOTNO { get; set; }
        public string MCODE { get; set; }
        public int ORGID { get; set; }
        public string TRANSNO { get; set; }
        public Nullable<int> TRANSLINE { get; set; }
        public string VENDORITEMCODE { get; set; }
        public string VENDORCODE { get; set; }
        public string VENDERLOTNO { get; set; }
        public int DATECODE { get; set; }
        public long LOTQTY { get; set; }
        public string ACTIVE { get; set; }
        public int EXDATE { get; set; }
        public int PRINTTIMES { get; set; }
        public string LASTPRINTUSER { get; set; }
        public int LASTPRINTDATE { get; set; }
        public int LASTPRINTTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string FACTORY { get; set; }
        public string STATUS { get; set; }
        public string CARTONTYPE { get; set; }
        public string VENDERDATE { get; set; }
        public string ITEMLOTSTATUS { get; set; }
        public string STACKCODE { get; set; }
        public string STORAGECODE { get; set; }
        public string SHIFTCODE { get; set; }
        public string SRC_LOTNO { get; set; }
        public Nullable<long> AVL_QTY { get; set; }
        public string INBILLNO { get; set; }
        public string MVD_CODE { get; set; }
        public string IS_RETURN { get; set; }
        public string FLAG { get; set; }
        public string MANUFACTURER { get; set; }
    }
}
