//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLINVINTRANSACTION
    {
        public string TRANSCODE { get; set; }
        public string RCARD { get; set; }
        public string CARTONCODE { get; set; }
        public string PALLETCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public string BUSINESSCODE { get; set; }
        public string STACKCODE { get; set; }
        public string STORAGECODE { get; set; }
        public string SSCODE { get; set; }
        public string COMPANY { get; set; }
        public string BUSINESSREASON { get; set; }
        public int SERIAL { get; set; }
        public int ORGID { get; set; }
        public string DELIVERUSER { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string RELATEDDOCUMENT { get; set; }
    }
}
