//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJIG
    {
        public string JIGCODE { get; set; }
        public string JIGSPECCODE { get; set; }
        public int MAXCOUNT { get; set; }
        public int USEDCOUNT { get; set; }
        public int ALERTCOUNT { get; set; }
        public int TOTALCOUNT { get; set; }
        public string STATUS { get; set; }
        public string STATUSCHGREASON { get; set; }
        public int STATUSCHGDATE { get; set; }
        public int STATUSCHGTIME { get; set; }
        public string RETREASON { get; set; }
        public string USEFLAG { get; set; }
        public string RESCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<decimal> CURRUNITQTY { get; set; }
        public string SSCODE { get; set; }
        public string OPEUSER { get; set; }
        public int MAXMDAY { get; set; }
        public int ALTERMDAY { get; set; }
        public Nullable<int> MAINTAINDATE { get; set; }
        public Nullable<int> MAINTAINTIME { get; set; }
        public string MAINTAINUSER { get; set; }
    }
}
