//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJOBLOG
    {
        public string JOBID { get; set; }
        public System.DateTime STARTDATETIME { get; set; }
        public System.DateTime ENDDATETIME { get; set; }
        public decimal USEDTIME { get; set; }
        public decimal PROCESSCOUNT { get; set; }
        public string RESULT { get; set; }
        public string ERRORMSG { get; set; }
        public decimal SERIAL { get; set; }
    }
}
