//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLJIGMAINTAIN
    {
        public string JIGCODE { get; set; }
        public string SEQ { get; set; }
        public string JIGSPECCODE { get; set; }
        public string STATUS { get; set; }
        public int MAXCOUNT { get; set; }
        public int USEDCOUNT { get; set; }
        public int TOTALCOUNT { get; set; }
        public string OLDSTATUS { get; set; }
        public string MAINTAINTYPE { get; set; }
        public string RETREASON { get; set; }
        public string ANALYSEREASON { get; set; }
        public string OPERMESSAGE { get; set; }
        public string SCRAPFLAG { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
