//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOTONWIP
    {
        public string LOTCODE { get; set; }
        public int LOTSEQ { get; set; }
        public int LOTQTY { get; set; }
        public int GOODQTY { get; set; }
        public int NGQTY { get; set; }
        public string MOCODE { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string ROUTECODE { get; set; }
        public string OPCODE { get; set; }
        public string SEGCODE { get; set; }
        public string SSCODE { get; set; }
        public string RESCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string BEGINSHIFTCODE { get; set; }
        public string ENDSHIFTCODE { get; set; }
        public string BEGINTPCODE { get; set; }
        public string ENDTPCODE { get; set; }
        public int BEGINSHIFTDAY { get; set; }
        public Nullable<int> ENDSHIFTDAY { get; set; }
        public string ACTION { get; set; }
        public string ACTIONRESULT { get; set; }
        public Nullable<int> NGTIMES { get; set; }
        public string MUSER { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string SHELFNO { get; set; }
        public string RMABILLCODE { get; set; }
        public Nullable<int> MOSEQ { get; set; }
        public Nullable<decimal> SERIAL { get; set; }
        public int PROCESSED { get; set; }
        public string COLLECTSTATUS { get; set; }
        public int BEGINDATE { get; set; }
        public int BEGINTIME { get; set; }
        public Nullable<int> ENDDATE { get; set; }
        public Nullable<int> ENDTIME { get; set; }
    }
}
