//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLLOT_ERROR
    {
        public string LOTNO { get; set; }
        public int LOTSEQ { get; set; }
        public string OQCLOTTYPE { get; set; }
        public int LOTSIZE { get; set; }
        public int SSIZE { get; set; }
        public decimal AQL { get; set; }
        public decimal AQL1 { get; set; }
        public decimal AQL2 { get; set; }
        public int ACCSIZE { get; set; }
        public int ACCSIZE1 { get; set; }
        public int ACCSIZE2 { get; set; }
        public int RJTSIZE { get; set; }
        public int RJTSIZE1 { get; set; }
        public int RJTSIZE2 { get; set; }
        public string LOTSTATUS { get; set; }
        public int LOTTIMES { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> DDATE { get; set; }
        public Nullable<int> DTIME { get; set; }
        public string DUSER { get; set; }
        public string PRODUCTIONTYPE { get; set; }
        public string OLDLOTNO { get; set; }
        public Nullable<decimal> AQL3 { get; set; }
        public Nullable<int> ACCSIZE3 { get; set; }
        public Nullable<int> RJTSIZE3 { get; set; }
        public Nullable<int> ORGID { get; set; }
        public Nullable<int> LOTCAPACITY { get; set; }
        public string LOTFROZEN { get; set; }
        public string MEMO { get; set; }
        public string CUSER { get; set; }
        public Nullable<int> CDATE { get; set; }
        public Nullable<int> CTIME { get; set; }
        public string SSCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string FROZENSTATUS { get; set; }
        public string FROZENREASON { get; set; }
        public Nullable<int> FROZENDATE { get; set; }
        public Nullable<int> FROZENTIME { get; set; }
        public string FROZENBY { get; set; }
        public string UNFROZENREASON { get; set; }
        public Nullable<int> UNFROZENDATE { get; set; }
        public Nullable<int> UNFROZENTIME { get; set; }
        public string UNFROZENBY { get; set; }
        public string RESCODE { get; set; }
        public Nullable<int> SHIFTDAY { get; set; }
        public string SHIFTCODE { get; set; }
    }
}
