//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMKEYPART
    {
        public string MITEMCODE { get; set; }
        public decimal SEQ { get; set; }
        public string RCARDSTART { get; set; }
        public string RCARDEND { get; set; }
        public string LOTNO { get; set; }
        public string PCBA { get; set; }
        public string BIOS { get; set; }
        public string VERSION { get; set; }
        public string VENDORITEMCODE { get; set; }
        public string VENDORCODE { get; set; }
        public string DATECODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string MOCODE { get; set; }
        public string MITEMNAME { get; set; }
        public string RCARDPREFIX { get; set; }
        public string SNSCALE { get; set; }
        public string TEMPLATENAME { get; set; }
    }
}
