//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMDL
    {
        public string MDLCODE { get; set; }
        public string PMDLCODE { get; set; }
        public string MDLVER { get; set; }
        public string MDLTYPE { get; set; }
        public string MDLSTATUS { get; set; }
        public string MDLDESC { get; set; }
        public int MDLSEQ { get; set; }
        public string MDLHFNAME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string ISSYS { get; set; }
        public string ISACTIVE { get; set; }
        public string FORMURL { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string ISRESTRAIN { get; set; }
    }
}
