//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMO2IMEILOG
    {
        public long SERIAL { get; set; }
        public long TSERIAL { get; set; }
        public string MOCODE { get; set; }
        public string IMEI1 { get; set; }
        public string IMEI2 { get; set; }
        public string MEID { get; set; }
        public string NETCODE { get; set; }
        public string PSN { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string ID3 { get; set; }
        public string ID4 { get; set; }
        public string ID5 { get; set; }
        public string TSN { get; set; }
        public string STATUS { get; set; }
        public int CDATE { get; set; }
        public int CTIME { get; set; }
        public string CUSER { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string SN { get; set; }
    }
}
