//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMO2SN
    {
        public long SERIAL { get; set; }
        public string MOCODE { get; set; }
        public string SN { get; set; }
        public string CODE1 { get; set; }
        public string CODE2 { get; set; }
        public string CODE3 { get; set; }
        public string PSN { get; set; }
        public short STATUS { get; set; }
        public string CUSER { get; set; }
        public Nullable<int> CDATE { get; set; }
        public Nullable<int> CTIME { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
