//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMOBOM
    {
        public string MOCODE { get; set; }
        public string ITEMCODE { get; set; }
        public int SEQ { get; set; }
        public string MOBITEMCODE { get; set; }
        public string MOBITEMECN { get; set; }
        public string MOBITEMNAME { get; set; }
        public string MOBITEMDESC { get; set; }
        public string MOBITEMSTATUS { get; set; }
        public string MOBITEMLOCATION { get; set; }
        public int MOBITEMEFFDATE { get; set; }
        public int MOBITEMEFFTIME { get; set; }
        public int MOBITEMINVDATE { get; set; }
        public int MOBITEMINVTIME { get; set; }
        public decimal MOBITEMQTY { get; set; }
        public string MOBSITEMCODE { get; set; }
        public string MOBITEMVER { get; set; }
        public string MOBITEMCONTYPE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string MOBOMITEMUOM { get; set; }
        public string OPCODE { get; set; }
        public string MOBOM { get; set; }
        public string MOBOMLINE { get; set; }
        public string MOFAC { get; set; }
        public string MORESOURCE { get; set; }
    }
}
