//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMO
    {
        public string MOCODE { get; set; }
        public string MOMEMO { get; set; }
        public string MOTYPE { get; set; }
        public string MODESC { get; set; }
        public string MOBIOSVER { get; set; }
        public string MOPCBAVER { get; set; }
        public decimal MOPLANQTY { get; set; }
        public decimal MOINPUTQTY { get; set; }
        public decimal MOSCRAPQTY { get; set; }
        public decimal MOACTQTY { get; set; }
        public int MOPLANSTARTDATE { get; set; }
        public int MOPLANENDDATE { get; set; }
        public int MOACTSTARTDATE { get; set; }
        public int MOACTENDDATE { get; set; }
        public string FACTORY { get; set; }
        public string CUSCODE { get; set; }
        public string CUSNAME { get; set; }
        public string CUSORDERNO { get; set; }
        public string CUSITEMCODE { get; set; }
        public string ORDERNO { get; set; }
        public int ORDERSEQ { get; set; }
        public string MOUSER { get; set; }
        public int MODOWNDATE { get; set; }
        public string MOSTATUS { get; set; }
        public string MOVER { get; set; }
        public string ISCONINPUT { get; set; }
        public string ISBOMPASS { get; set; }
        public int IDMERGERULE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string ITEMCODE { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> MORELEASEDATE { get; set; }
        public Nullable<int> MORELEASETIME { get; set; }
        public string MOPENDINGCAUSE { get; set; }
        public Nullable<int> MOIMPORTDATE { get; set; }
        public Nullable<int> MOIMPORTTIME { get; set; }
        public Nullable<decimal> OFFMOQTY { get; set; }
        public Nullable<int> ISCOMPARESOFT { get; set; }
        public string RMABILLCODE { get; set; }
        public Nullable<int> MOSEQ { get; set; }
        public string REMOCODE { get; set; }
        public string REMOITEMCODE { get; set; }
        public string REMOITEMDESC { get; set; }
        public string REMOLOTNO { get; set; }
        public string REMOENABLED { get; set; }
        public int ORGID { get; set; }
        public string MOBOM { get; set; }
        public string MOOP { get; set; }
        public string ITEMDESC { get; set; }
        public Nullable<decimal> MOPLANSTARTTIME { get; set; }
        public Nullable<decimal> MOPLANENDTIME { get; set; }
        public string MOPLANLINE { get; set; }
        public string EATTRIBUTE2 { get; set; }
        public string EATTRIBUTE3 { get; set; }
        public string EATTRIBUTE4 { get; set; }
        public string EATTRIBUTE5 { get; set; }
        public string EATTRIBUTE6 { get; set; }
        public string MOREMARK { get; set; }
        public string COLOR { get; set; }
        public string SOFTEDITION { get; set; }
        public string HWID { get; set; }
        public string PLATFORM { get; set; }
        public string SHIPTO { get; set; }
        public string SAVEMACBT { get; set; }
        public string SAVEIMEI { get; set; }
        public string SHIPCOUNTRY { get; set; }
        public string MOPLANCODE { get; set; }
        public string DEVICE { get; set; }
        public string MIUINUM { get; set; }
        public string USERDATAVERSION { get; set; }
        public string CUSTOMEROPTION { get; set; }
    }
}
