//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMATERIALRECEIVE
    {
        public string IQCNO { get; set; }
        public string STNO { get; set; }
        public int STLINE { get; set; }
        public string ITEMCODE { get; set; }
        public Nullable<long> REALRECEIVEQTY { get; set; }
        public string RECEIVEMEMO { get; set; }
        public int ACCOUNTDATE { get; set; }
        public int VOUCHERDATE { get; set; }
        public string ORDERNO { get; set; }
        public Nullable<decimal> ORDERLINE { get; set; }
        public int ORGID { get; set; }
        public string STORAGEID { get; set; }
        public string UNIT { get; set; }
        public string FLAG { get; set; }
        public string TRANSACTIONCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
