//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMENU
    {
        public string MENUCODE { get; set; }
        public string MDLCODE { get; set; }
        public string PMENUCODE { get; set; }
        public string MENUDESC { get; set; }
        public int MENUSEQ { get; set; }
        public string MENUTYPE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string VISIBILITY { get; set; }
    }
}
