//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMOINFO
    {
        public int FORM_NO { get; set; }
        public string FORM_APPLICANT { get; set; }
        public Nullable<System.DateTime> CREATED_ON { get; set; }
        public Nullable<System.DateTime> CHANGED_ON { get; set; }
        public Nullable<System.DateTime> APPLIED_ON { get; set; }
        public Nullable<System.DateTime> AP_ON { get; set; }
        public Nullable<System.DateTime> CL_ON { get; set; }
        public string FILLER { get; set; }
        public string APPLIER_DEPT_CODE { get; set; }
        public string APPLIER_DEPT_NAME { get; set; }
        public string BELONG_SYSTEM { get; set; }
        public string LOCATION_ID { get; set; }
        public string LOCATION_NAME { get; set; }
        public string FORM_NO_GEN { get; set; }
        public string PROCESSING_SQUARE_ID { get; set; }
        public string PROCESSING_SQUARE_NAME { get; set; }
        public string PROCESSING_CATEGORY_ID { get; set; }
        public string PROCESSING_CATEGORY_NAME { get; set; }
        public string PRODUCTION_NATURE_ID { get; set; }
        public string PRODUCTION_NATURE_NAME { get; set; }
        public string NOTE { get; set; }
        public string PROJECT_CODE { get; set; }
        public string PRODUCTS_PN { get; set; }
        public Nullable<int> PRODUCTION_QUANTITY { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public string SPECIAL_NEEDS_CPJL { get; set; }
        public string PCBA_MATERIALS { get; set; }
        public string ASSEMBLY_BOM_NO { get; set; }
        public string SOFTWARE_VERSION_NO { get; set; }
        public string PACKAGING_BOM_NO { get; set; }
        public string SPECIAL_NEEDS_XMJL { get; set; }
        public string PROCESS { get; set; }
        public string IMEI_HAODUAN { get; set; }
        public string UC1 { get; set; }
        public string UC2 { get; set; }
        public string UC3 { get; set; }
        public string UC4 { get; set; }
        public string UC5 { get; set; }
        public string SHIYEBU_ID { get; set; }
        public string XIANGMUJINGLI_ID { get; set; }
        public string ZHENJIGONGCHENGBU_ID { get; set; }
        public string ZHILIANGCEHUA_ID { get; set; }
        public Nullable<System.DateTime> STARTS_DATE { get; set; }
        public string BAOFEI_ID { get; set; }
        public string BAOFEI_NAME { get; set; }
        public string CTP_VERSION { get; set; }
        public string PQE_APPROVER { get; set; }
        public string NEWPM_APPROVER { get; set; }
        public string TRY_PRO { get; set; }
        public string PRO_IMPROVE { get; set; }
        public string REVIEW { get; set; }
        public string SHIFOU_FIRST { get; set; }
        public string ARCH_BOM { get; set; }
        public string ASS_BOM { get; set; }
        public string PACK_BOM { get; set; }
        public string BOM_REQUIRE { get; set; }
        public string SOP_REALEASE { get; set; }
        public string CLAMP_TEST { get; set; }
        public string SOP_REQUIRE { get; set; }
        public string CUST_SRV_APPROVER { get; set; }
        public Nullable<int> CHAOGUO { get; set; }
        public Nullable<System.DateTime> GCB_DATE { get; set; }
        public string BFWLQL { get; set; }
        public string BFWLQLNR { get; set; }
        public string STATE { get; set; }
    }
}
