//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMFROZEN
    {
        public string FROZENCODE { get; set; }
        public string MCARD { get; set; }
        public string MCODE { get; set; }
        public string VENDORCODE { get; set; }
        public Nullable<decimal> RECDATE { get; set; }
        public string MCONTROLTYPE { get; set; }
        public string STATUS { get; set; }
        public string FROZENREASON { get; set; }
        public int FROZENDATE { get; set; }
        public int FROZENTIME { get; set; }
        public string FROZENBY { get; set; }
        public string UNFROZENREASON { get; set; }
        public Nullable<int> UNFROZENDATE { get; set; }
        public Nullable<int> UNFROZENTIME { get; set; }
        public string UNFROZENBY { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public int ORGID { get; set; }
    }
}
