//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMO2RCARDLINK
    {
        public string MOCODE { get; set; }
        public string RCARD { get; set; }
        public int PRINTTIMES { get; set; }
        public string LASTPRINTUSER { get; set; }
        public Nullable<int> LASTPRINTDATE { get; set; }
        public Nullable<int> LASTPRINTTIME { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
    }
}
