//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMO2LOTLINK
    {
        public string MOCODE { get; set; }
        public string LOTNO { get; set; }
        public long LOTQTY { get; set; }
        public string LOTSTATUS { get; set; }
        public int PRINTTIMES { get; set; }
        public string LASTPRINTUSER { get; set; }
        public Nullable<int> LASTPRINTDATE { get; set; }
        public Nullable<int> LASTPRINTTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
