//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMATERIAL
    {
        public string MCODE { get; set; }
        public string MNAME { get; set; }
        public string MDESC { get; set; }
        public string MUOM { get; set; }
        public string MTYPE { get; set; }
        public string MMACHINETYPE { get; set; }
        public string MVOLUME { get; set; }
        public string MMODELCODE { get; set; }
        public string MEXPORTIMPORT { get; set; }
        public string MMODELGROUP { get; set; }
        public string MGROUP { get; set; }
        public string MGROUPDESC { get; set; }
        public string MCONTROLTYPE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public int ORGID { get; set; }
        public string MPARSETYPE { get; set; }
        public string CHECKSTATUS { get; set; }
        public string MCHECKTYPE { get; set; }
        public Nullable<int> SNLENGTH { get; set; }
        public string VENDORCODE { get; set; }
        public string ROHS { get; set; }
        public string NEEDVENDOR { get; set; }
        public Nullable<int> MSHELFLIFE { get; set; }
        public string ISSMT { get; set; }
        public Nullable<int> MINQTY { get; set; }
        public string ESD { get; set; }
        public string MSD { get; set; }
        public string LOTFIXSTR { get; set; }
        public string SWAPDATECODE { get; set; }
        public Nullable<decimal> MSDMAXEXPTIME { get; set; }
        public string ISSPECIALSYMBOL { get; set; }
        public string ALLOWREPLACE { get; set; }
        public string MATERIALTYPECLASS { get; set; }
        public Nullable<decimal> STATICTIME { get; set; }
    }
}
