//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOPBOMDETAIL
    {
        public string OPID { get; set; }
        public string ITEMCODE { get; set; }
        public string OBCODE { get; set; }
        public string OPBOMVER { get; set; }
        public string OBITEMCODE { get; set; }
        public string OPCODE { get; set; }
        public string OBITEMNAME { get; set; }
        public string OBITEMECN { get; set; }
        public string OBITEMUOM { get; set; }
        public decimal OBITEMQTY { get; set; }
        public string OBSITEMCODE { get; set; }
        public string OBITEMVER { get; set; }
        public string OBITEMTYPE { get; set; }
        public string OBITEMCONTYPE { get; set; }
        public int OBITEMEFFDATE { get; set; }
        public int OBITEMEFFTIME { get; set; }
        public int OBITEMINVDATE { get; set; }
        public int OBITEMINVTIME { get; set; }
        public string ISITEMCHECK { get; set; }
        public string ITEMCHECKVALUE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public int ACTIONTYPE { get; set; }
        public string CHECKSTATUS { get; set; }
        public int ORGID { get; set; }
        public int OBITEMSEQ { get; set; }
        public string OBPARSETYPE { get; set; }
        public string OBCHECKTYPE { get; set; }
        public int OBVALID { get; set; }
        public Nullable<int> SNLENGTH { get; set; }
        public string NEEDVENDOR { get; set; }
        public Nullable<int> LINDEX { get; set; }
        public string LSTRING { get; set; }
        public string ALLOWSPLIT { get; set; }
        public string ISFORBITBUCKLE { get; set; }
        public string ISSAMERCARD { get; set; }
        public string MATERIALTYPECLASS { get; set; }
        public string ISSPECIALSYMBOL { get; set; }
        public string ALLOWREPLACE { get; set; }
        public string LOTFIXSTR { get; set; }
        public Nullable<int> LINDEX1 { get; set; }
        public string LSTRING1 { get; set; }
        public string BOOKINGIMEI { get; set; }
        public string PHANTOM { get; set; }
    }
}
