//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLOBA
    {
        public decimal SERIAL { get; set; }
        public string MOCODE { get; set; }
        public string PALLETCODE { get; set; }
        public string CARTONCODE { get; set; }
        public string RESCODE { get; set; }
        public string SSCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string OPCODE { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        public Nullable<decimal> RCARDCOUNT { get; set; }
    }
}
