//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLONWIPCARDSPLIT
    {
        public string RCARD { get; set; }
        public string MOCODE { get; set; }
        public int RCARDSEQ { get; set; }
        public string TCARD { get; set; }
        public int TCARDSEQ { get; set; }
        public string SCARD { get; set; }
        public int SCARDSEQ { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string ROUTECODE { get; set; }
        public string OPCODE { get; set; }
        public string SEGCODE { get; set; }
        public string SSCODE { get; set; }
        public string RESCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string SHIFTCODE { get; set; }
        public string TPCODE { get; set; }
        public string IDMERGETYPE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
