//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLORTSAMPLINGCONFIG
    {
        public string MATERIALCODE { get; set; }
        public string DIMENSION { get; set; }
        public string OPCODE { get; set; }
        public string SYMBOL1 { get; set; }
        public int SAMPLEQTY1 { get; set; }
        public int CHECKQTY1 { get; set; }
        public string SYMBOL2 { get; set; }
        public int SAMPLEQTY2 { get; set; }
        public int CHECKQTY2 { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
