//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLONWIPLOTTRANS
    {
        public decimal SERIAL { get; set; }
        public string LOTCODE { get; set; }
        public string MOCODE { get; set; }
        public int LOTSEQ { get; set; }
        public string TLOTCODE { get; set; }
        public Nullable<int> TLOTSEQ { get; set; }
        public long TLOTQTY { get; set; }
        public long QTY { get; set; }
        public string ROUTECODE { get; set; }
        public string OPCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string OPERATIONTYPE { get; set; }
    }
}
