//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRINTTEMPLATEPARAMLOG
    {
        public decimal SERIAL { get; set; }
        public string L_USER { get; set; }
        public string L_TYPE { get; set; }
        public string L_DATE { get; set; }
        public string ITEMCODE { get; set; }
        public string TEMPLATENAME { get; set; }
        public string PARAMCODE { get; set; }
        public string PARAMVALUE { get; set; }
        public string PARAMDESC { get; set; }
        public string PARAMTYPE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
