//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPPCODE
    {
        public string MCODE { get; set; }
        public string MNAME { get; set; }
        public Nullable<int> LINDEX { get; set; }
        public string LSTRING { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MUSER { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> LINDEX1 { get; set; }
        public string LSTRING1 { get; set; }
        public string PHANTOM { get; set; }
        public string WITHBARCODE { get; set; }
        public string BUCKLE { get; set; }
    }
}
