//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPAUSE2RCARD
    {
        public string PAUSECODE { get; set; }
        public string SERIALNO { get; set; }
        public string ITEMCODE { get; set; }
        public string CANCELSEQ { get; set; }
        public string BOM { get; set; }
        public string MOCODE { get; set; }
        public string STATUS { get; set; }
        public string CANCELREASON { get; set; }
        public string PUSER { get; set; }
        public int PDATE { get; set; }
        public int PTIME { get; set; }
        public string CUSER { get; set; }
        public Nullable<int> CDATE { get; set; }
        public Nullable<int> CTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
