//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRPTSOQTY
    {
        public string MOCODE { get; set; }
        public int SHIFTDAY { get; set; }
        public string ITEMCODE { get; set; }
        public decimal TBLMESENTITYLIST_SERIAL { get; set; }
        public decimal MOINPUTCOUNT { get; set; }
        public decimal MOOUTPUTCOUNT { get; set; }
        public decimal MOLINEOUTPUTCOUNT { get; set; }
        public decimal MOWHITECARDCOUNT { get; set; }
        public decimal MOOUTPUTWHITECARDCOUNT { get; set; }
        public decimal LINEINPUTCOUNT { get; set; }
        public decimal LINEOUTPUTCOUNT { get; set; }
        public decimal OPCOUNT { get; set; }
        public decimal OPWHITECARDCOUNT { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
