//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRPTVFILTERUI
    {
        public string RPTID { get; set; }
        public int SEQ { get; set; }
        public string INPUTTYPE { get; set; }
        public string INPUTNAME { get; set; }
        public int SQLFLTSEQ { get; set; }
        public string UITYPE { get; set; }
        public string SELQTYPE { get; set; }
        public string LISTSRCTYPE { get; set; }
        public string LISTSVAL { get; set; }
        public int LISTDSRC { get; set; }
        public string LISTDTEXTCOL { get; set; }
        public string LISTDVALUECOL { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string CHECKEXIST { get; set; }
    }
}
