//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRPTVCONNECT
    {
        public int DATACONNECTID { get; set; }
        public string CONNECTNAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string SERVERTYPE { get; set; }
        public string SERVICENAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DEFAULTDATABASE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
