//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRPTVDATAFMT
    {
        public string FORMATID { get; set; }
        public string FONTFAMILY { get; set; }
        public int FONTSIZE { get; set; }
        public string TEXTDECORATION { get; set; }
        public string FONTWEIGHT { get; set; }
        public string FONTSTYLE { get; set; }
        public string COLOR { get; set; }
        public string BCOLOR { get; set; }
        public string TEXTALIGN { get; set; }
        public string VERTICALALIGN { get; set; }
        public string TEXTFORMAT { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public Nullable<decimal> COLUMNWIDTH { get; set; }
        public string BORDERSTYLE { get; set; }
        public string TEXTEXPRESS { get; set; }
    }
}
