//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRES
    {
        public string RESCODE { get; set; }
        public string RESDESC { get; set; }
        public string RESGROUP { get; set; }
        public string RESTYPE { get; set; }
        public string SEGCODE { get; set; }
        public string SSCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string REWORKROUTECODE { get; set; }
        public int ORGID { get; set; }
        public string REWORKCODE { get; set; }
        public string DCTCODE { get; set; }
        public string CREWCODE { get; set; }
        public string COMPUTERNAME { get; set; }
        public string COMPUTERMAC { get; set; }
        public string COMPUTERIP { get; set; }
        public string JIGCONTROL { get; set; }
        public string FACERCONTROL { get; set; }
        public string ARMORPLATECONTROL { get; set; }
    }
}
