//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLREWORKSHEET
    {
        public string REWORKCODE { get; set; }
        public string MOCODE { get; set; }
        public string CUSER { get; set; }
        public int CDATE { get; set; }
        public int CTIME { get; set; }
        public string STATUS { get; set; }
        public string REWORKSCODE { get; set; }
        public string REWORKTYPE { get; set; }
        public string NEWMOCODE { get; set; }
        public string NEWROUTECODE { get; set; }
        public string NEWOPCODE { get; set; }
        public string NEWOPBOMCODE { get; set; }
        public string NEWOPBOMVER { get; set; }
        public int REWORKHC { get; set; }
        public string DEPARTMENT { get; set; }
        public string CONTENT { get; set; }
        public Nullable<int> REWORKDATE { get; set; }
        public Nullable<int> REWORKTIME { get; set; }
        public int REWORKQTY { get; set; }
        public int REWORKMAXQTY { get; set; }
        public int REWORKREALQTY { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string ITEMCODE { get; set; }
        public string REWORKREASON { get; set; }
        public string REASONANALYSE { get; set; }
        public string SOLUTION { get; set; }
        public string NEEDCHECK { get; set; }
        public string LOTLIST { get; set; }
        public string AUTOLOTNO { get; set; }
        public string DUTYCODE { get; set; }
    }
}
