//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLREJECT2ERRORCODE
    {
        public string RCARD { get; set; }
        public int RCARDSEQ { get; set; }
        public string ERRORCODEGROUP { get; set; }
        public string ECODE { get; set; }
        public string MOCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string LOTNO { get; set; }
        public Nullable<int> LOTSEQ { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
