//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRESRELEASELOG
    {
        public decimal SERIAL { get; set; }
        public string RESCODE { get; set; }
        public string COMPUTERNAME { get; set; }
        public string COMPUTERMAC { get; set; }
        public string COMPUTERIP { get; set; }
        public string LOGINUSER { get; set; }
        public Nullable<int> LOGINDATE { get; set; }
        public Nullable<int> LOGINTIME { get; set; }
        public string RELEASEUSER { get; set; }
        public Nullable<int> RELEASEDATE { get; set; }
        public Nullable<int> RELEASETIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string JIGCODE { get; set; }
    }
}
