//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRMADETIAL
    {
        public string RMABILLCODE { get; set; }
        public string SERVERCODE { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string RCARD { get; set; }
        public string HANDELCODE { get; set; }
        public string COMPISSUE { get; set; }
        public string CUSTOMCODE { get; set; }
        public string COMFROM { get; set; }
        public short MAINTENANCE { get; set; }
        public Nullable<int> WHRECEIVEDATE { get; set; }
        public string SUBCOMPANY { get; set; }
        public string REMOCODE { get; set; }
        public string ERRORCODE { get; set; }
        public string ISINSHELFLIFE { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
