//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLRPTRESECG
    {
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public int SHIFTDAY { get; set; }
        public string SHIFTCODE { get; set; }
        public string TPCODE { get; set; }
        public string OPCODE { get; set; }
        public string RESCODE { get; set; }
        public string SEGCODE { get; set; }
        public string SSCODE { get; set; }
        public string ECGCODE { get; set; }
        public string ECCODE { get; set; }
        public int TPBTIME { get; set; }
        public int TPETIME { get; set; }
        public int MONTH { get; set; }
        public int WEEK { get; set; }
        public int DAY { get; set; }
        public int NGTIMES { get; set; }
        public int EATTRIBUTE1 { get; set; }
        public int EATTRIBUTE2 { get; set; }
        public int EATTRIBUTE3 { get; set; }
    }
}
