//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLREEL
    {
        public string REELNO { get; set; }
        public string PARTNO { get; set; }
        public decimal QTY { get; set; }
        public decimal USEDQTY { get; set; }
        public string LOTNO { get; set; }
        public string DATECODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string USEDFLAG { get; set; }
        public string MOCODE { get; set; }
        public string SSCODE { get; set; }
        public string ISSPECIAL { get; set; }
        public string MEMO { get; set; }
        public Nullable<decimal> CHECKDIFFQTY { get; set; }
        public string FACTORY { get; set; }
        public string MSDRESETUSER { get; set; }
    }
}
