//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLREELCHKLOG
    {
        public int CHECKID { get; set; }
        public string MOCODE { get; set; }
        public string SSCODE { get; set; }
        public string REELNO { get; set; }
        public string MATERIALCODE { get; set; }
        public decimal REELQTY { get; set; }
        public decimal REELCURRQTY { get; set; }
        public string ISSPECIAL { get; set; }
        public string MEMO { get; set; }
        public string GETOUTUSER { get; set; }
        public int GETOUTDATE { get; set; }
        public int GETOUTTIME { get; set; }
        public decimal REELLEFTQTY { get; set; }
        public decimal REELACTQTY { get; set; }
        public string ISCHECKED { get; set; }
        public string CHECKUSER { get; set; }
        public int CHECKDATE { get; set; }
        public int CHECKTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
