//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSMTLOADCHECKLOG
    {
        public decimal SERIAL { get; set; }
        public string MOCODE { get; set; }
        public string SSCODE { get; set; }
        public string MACHINECODE { get; set; }
        public string MACHINESTATIONCODE { get; set; }
        public string REELNO { get; set; }
        public string CHECKRESULT { get; set; }
        public string FAILREASON { get; set; }
        public string CUSER { get; set; }
        public int CDATE { get; set; }
        public int CTIME { get; set; }
        public string CRESCODE { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string CHKFLAG { get; set; }
    }
}
