//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSMTSENSORQTY
    {
        public string PRODUCTCODE { get; set; }
        public string SSCODE { get; set; }
        public string MOCODE { get; set; }
        public int SHIFTDAY { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string SHIFTCODE { get; set; }
        public string TPCODE { get; set; }
        public int TPBTIME { get; set; }
        public int TPETIME { get; set; }
        public int TPSEQ { get; set; }
        public int MOBDATE { get; set; }
        public int MOBTIME { get; set; }
        public int MOEDATE { get; set; }
        public int MOETIME { get; set; }
        public decimal QTY { get; set; }
        public string MAINTAINUSER { get; set; }
        public int MAINTAINDATE { get; set; }
        public int MAINTAINTIME { get; set; }
        public string DIFFREASON { get; set; }
        public string DIFFMUSER { get; set; }
        public Nullable<int> DIFFMDATE { get; set; }
        public Nullable<int> DIFFMTIME { get; set; }
    }
}
