//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSBOM
    {
        public string ITEMCODE { get; set; }
        public string SBITEMCODE { get; set; }
        public string SBSITEMCODE { get; set; }
        public decimal SBITEMQTY { get; set; }
        public int SBITEMEFFDATE { get; set; }
        public string SBWH { get; set; }
        public Nullable<int> SEQ { get; set; }
        public string SBITEMECN { get; set; }
        public string SBITEMNAME { get; set; }
        public string SBITEMDESC { get; set; }
        public string SBITEMSTATUS { get; set; }
        public string SBITEMLOCATION { get; set; }
        public int SBITEMEFFTIME { get; set; }
        public int SBITEMINVDATE { get; set; }
        public int SBITEMINVTIME { get; set; }
        public string SBITEMUOM { get; set; }
        public string SBITEMVER { get; set; }
        public string SBITEMCONTYPE { get; set; }
        public string SBPITEMCODE { get; set; }
        public string ALPGR { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public int ORGID { get; set; }
        public string SBOMVER { get; set; }
        public string ITEMDESC { get; set; }
        public string SBFACTORY { get; set; }
        public string SBUSAGE { get; set; }
        public string SBITEMPROJECT { get; set; }
        public string SBITEMSEQ { get; set; }
        public string LOCATION { get; set; }
        public string TRACELEVEL { get; set; }
    }
}
