//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSYSPARAM
    {
        public string PARAMCODE { get; set; }
        public string PARAMGROUPCODE { get; set; }
        public string PARAMALIAS { get; set; }
        public string PARAMDESC { get; set; }
        public string PARAMVALUE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string ISACTIVE { get; set; }
        public string ISSYS { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string PARENTPARAM { get; set; }
    }
}
