//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSYSERROR
    {
        public string SYSERRCODE { get; set; }
        public string ERRMSG { get; set; }
        public string INNERERRMSG { get; set; }
        public string TRGMDLCODE { get; set; }
        public string TRIGACTION { get; set; }
        public string SENDUSER { get; set; }
        public int SENDDATE { get; set; }
        public int SENDTIME { get; set; }
        public string ISRES { get; set; }
        public string RESNOTES { get; set; }
        public string RESUSER { get; set; }
        public Nullable<int> RESDATE { get; set; }
        public Nullable<int> RESTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
