//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSOLDERPASTEPRO
    {
        public string SPPKID { get; set; }
        public string SOLDERPASTEID { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string LINECODE { get; set; }
        public string MOCODE { get; set; }
        public string STATUS { get; set; }
        public string SPTYPE { get; set; }
        public string LOTNO { get; set; }
        public string OPENUSER { get; set; }
        public string RETRUNUSER { get; set; }
        public Nullable<int> RETURNDATE { get; set; }
        public Nullable<int> RETURNTIME { get; set; }
        public Nullable<int> OPENDATE { get; set; }
        public Nullable<int> OPENTIME { get; set; }
        public string AGITAEUSER { get; set; }
        public Nullable<int> AGITATEDATE { get; set; }
        public Nullable<int> AGITATETIME { get; set; }
        public string UNVEILUSER { get; set; }
        public Nullable<int> UNVEILMDATE { get; set; }
        public Nullable<int> UNVEILTIME { get; set; }
        public string RESAVEUSER { get; set; }
        public Nullable<int> RESAVEDATE { get; set; }
        public Nullable<int> RESAVETIME { get; set; }
        public string UNAVIALUSER { get; set; }
        public Nullable<int> UNAVIALDATE { get; set; }
        public Nullable<int> UNAVIALTIME { get; set; }
        public string MUSER { get; set; }
        public Nullable<decimal> RETURNTIMESPAN { get; set; }
        public Nullable<decimal> RETURNCOUNTTIME { get; set; }
        public Nullable<decimal> VEILTIMESPAN { get; set; }
        public Nullable<decimal> VEILCOUNTTIME { get; set; }
        public Nullable<decimal> UNVEILTIMESPAN { get; set; }
        public Nullable<decimal> UNVEILCOUNTTIME { get; set; }
        public int EXPIREDDATE { get; set; }
        public string MEMO { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
