//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSMTTARGETQTY
    {
        public string MOCODE { get; set; }
        public string SSCODE { get; set; }
        public string TPCODE { get; set; }
        public string PRODUCTCODE { get; set; }
        public string SEGCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string SHIFTCODE { get; set; }
        public int TPBTIME { get; set; }
        public int TPETIME { get; set; }
        public int TPSEQ { get; set; }
        public string TPDESC { get; set; }
        public decimal TPQTY { get; set; }
        public decimal QTYPERHOUR { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
