//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTDWORKTIME
    {
        public decimal SERIAL { get; set; }
        public string ITEMCODE { get; set; }
        public string SSCODE { get; set; }
        public string PROCESS { get; set; }
        public string PROCESSTYPE { get; set; }
        public string PROJECT { get; set; }
        public string ITEMDESC { get; set; }
        public Nullable<decimal> CYCLETIME { get; set; }
        public Nullable<decimal> MANCOUNTDIRECT { get; set; }
        public Nullable<decimal> MANCOUNTONLINE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string MEMOS { get; set; }
    }
}
