//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSHIFT
    {
        public string SHIFTCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public int SHIFTSEQ { get; set; }
        public string SHIFTDESC { get; set; }
        public int SHIFTBTIME { get; set; }
        public int SHIFTETIME { get; set; }
        public string ISOVERDAY { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    }
}
