//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSPCITEMSPEC
    {
        public string ITEMCODE { get; set; }
        public string OBJECTCODE { get; set; }
        public int GROUPSEQ { get; set; }
        public string CONDITIONNAME { get; set; }
        public decimal UCL { get; set; }
        public decimal LCL { get; set; }
        public decimal USL { get; set; }
        public decimal LSL { get; set; }
        public string LIMITUPONLY { get; set; }
        public string LIMITLOWONLY { get; set; }
        public string AUTOCL { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
    
        public virtual TBLSPCOBJECT TBLSPCOBJECT { get; set; }
    }
}
