//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSS
    {
        public string SSCODE { get; set; }
        public int SSSEQ { get; set; }
        public string SSDESC { get; set; }
        public string SEGCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string SSTYPE { get; set; }
        public string CARTONNOCODE { get; set; }
        public Nullable<int> ORGID { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string BIGSSCODE { get; set; }
        public string SAVEINSTOCK { get; set; }
        public string IPRANGE { get; set; }
    }
}
