//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSHIPTOSTOCK
    {
        public string ITEMCODE { get; set; }
        public int ORGID { get; set; }
        public string VENDORCODE { get; set; }
        public int EFFDATE { get; set; }
        public int IVLDATE { get; set; }
        public string ACTIVE { get; set; }
        public string MUSER { get; set; }
        public decimal MDATE { get; set; }
        public decimal MTIME { get; set; }
    }
}
