//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTRY
    {
        public string TRYCODE { get; set; }
        public string STATUS { get; set; }
        public string ITEMCODE { get; set; }
        public Nullable<decimal> PLANQTY { get; set; }
        public Nullable<decimal> ACTUALQTY { get; set; }
        public string TRYDOCUMENT { get; set; }
        public string DEPT { get; set; }
        public string VENDORNAME { get; set; }
        public string RESULT { get; set; }
        public string MEMO { get; set; }
        public string LINKLOT { get; set; }
        public string CUSER { get; set; }
        public int CDATE { get; set; }
        public int CTIME { get; set; }
        public string RUSER { get; set; }
        public Nullable<int> RDATE { get; set; }
        public Nullable<int> RTIME { get; set; }
        public string FUSER { get; set; }
        public Nullable<int> FDATE { get; set; }
        public Nullable<int> FTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string TRYTYPE { get; set; }
        public string TRYREASON { get; set; }
        public string SOFTVERSION { get; set; }
        public string WAITTRY { get; set; }
        public string CHANGE { get; set; }
        public string BURNINDURATION { get; set; }
    }
}
