//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTESTDATA
    {
        public decimal SERIAL { get; set; }
        public string RCARD { get; set; }
        public string MOCODE { get; set; }
        public decimal SHIFTDAY { get; set; }
        public string ITEMCODE { get; set; }
        public decimal TBLMESENTITYLIST_SERIAL { get; set; }
        public string DEVICENO { get; set; }
        public string CKGROUP { get; set; }
        public string CKITEMCODE { get; set; }
        public string PARAM { get; set; }
        public Nullable<decimal> USL { get; set; }
        public Nullable<decimal> LSL { get; set; }
        public string TESTINGVALUE { get; set; }
        public string TESTINGRESULT { get; set; }
        public int TESTINGDATE { get; set; }
        public int TESTINGTIME { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
    }
}
