//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTSSPLITITEM
    {
        public string TSID { get; set; }
        public int ITEMSEQ { get; set; }
        public string RCARD { get; set; }
        public int RCARDSEQ { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public int LOCPOINT { get; set; }
        public string RRESCODE { get; set; }
        public string ROPCODE { get; set; }
        public string MITEMCODE { get; set; }
        public string MCARD { get; set; }
        public string MCARDTYPE { get; set; }
        public int QTY { get; set; }
        public string DATECODE { get; set; }
        public string PCBA { get; set; }
        public string BIOS { get; set; }
        public string REVERSION { get; set; }
        public string VENDORITEMCODE { get; set; }
        public string VENDORCODE { get; set; }
        public string MEMO { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> OPENQTY { get; set; }
        public Nullable<int> SCRAPQTY { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
