//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTS
    {
        public string TSID { get; set; }
        public string RCARD { get; set; }
        public int RCARDSEQ { get; set; }
        public string TCARD { get; set; }
        public int TCARDSEQ { get; set; }
        public string SCARD { get; set; }
        public int SCARDSEQ { get; set; }
        public string CARDTYPE { get; set; }
        public string RRCARD { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public string FRMROUTECODE { get; set; }
        public string FRMOPCODE { get; set; }
        public string FRMSEGCODE { get; set; }
        public string FRMSSCODE { get; set; }
        public string FRMRESCODE { get; set; }
        public string SHIFTTYPECODE { get; set; }
        public string SHIFTCODE { get; set; }
        public string TPCODE { get; set; }
        public int SHIFTDAY { get; set; }
        public string FRMUSER { get; set; }
        public string FRMMEMO { get; set; }
        public int FRMDATE { get; set; }
        public int FRMTIME { get; set; }
        public string FRMINPUTTYPE { get; set; }
        public int TSTIMES { get; set; }
        public string TSSTATUS { get; set; }
        public string TSUSER { get; set; }
        public Nullable<int> TSDATE { get; set; }
        public Nullable<int> TSTIME { get; set; }
        public string TSMEMO { get; set; }
        public string CRESCODE { get; set; }
        public string COPCODE { get; set; }
        public string CONFIRMUSER { get; set; }
        public Nullable<int> CONFIRMTIME { get; set; }
        public Nullable<int> CONFIRMDATE { get; set; }
        public string REFMOCODE { get; set; }
        public string REFROUTECODE { get; set; }
        public string REFOPCODE { get; set; }
        public string REFRESCODE { get; set; }
        public string TRANSSTATUS { get; set; }
        public string TFFULLPATH { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string TSRESCODE { get; set; }
        public string SCRAPCAUSE { get; set; }
        public Nullable<short> FRMMONTH { get; set; }
        public Nullable<short> FRMWEEK { get; set; }
        public string RMABILLCODE { get; set; }
        public string FRMOUTROUTECODE { get; set; }
        public Nullable<int> MOSEQ { get; set; }
        public string TSTYPE { get; set; }
        public string TSREPAIRUSER { get; set; }
        public Nullable<int> TSREPAIRMDATE { get; set; }
        public Nullable<int> TSREPAIRMTIME { get; set; }
        public Nullable<decimal> SERIAL { get; set; }
    }
}
