//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTSERRORCAUSE2COM
    {
        public string ECSCODE { get; set; }
        public string ECGCODE { get; set; }
        public string ECODE { get; set; }
        public string TSID { get; set; }
        public string ECSGCODE { get; set; }
        public string ERRORCOMPONENT { get; set; }
        public string RCARD { get; set; }
        public Nullable<int> RCARDSEQ { get; set; }
        public string MODELCODE { get; set; }
        public string ITEMCODE { get; set; }
        public string MOCODE { get; set; }
        public string RRESCODE { get; set; }
        public string ROPCODE { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
