//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLWMSITEMISCOM
    {
        public decimal SERIAL { get; set; }
        public string MODEL { get; set; }
        public string PN { get; set; }
        public string COLOR { get; set; }
        public string IMEI { get; set; }
        public int PDATE { get; set; }
        public int PTIME { get; set; }
        public string IMEI1 { get; set; }
        public string SNCODE { get; set; }
        public string OPERATOR { get; set; }
        public string BN { get; set; }
        public string MO { get; set; }
        public string SO { get; set; }
        public string FLAG { get; set; }
    }
}
