//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLWAREHOURSE
    {
        public string WHCODE { get; set; }
        public string FACCODE { get; set; }
        public string WHDESC { get; set; }
        public string WHTYPE { get; set; }
        public string MEMO { get; set; }
        public string LCYCLECODE { get; set; }
        public Nullable<int> LCYCLEDATE { get; set; }
        public Nullable<int> LCYCLETIME { get; set; }
        public string WHSTATUS { get; set; }
        public Nullable<int> USECOUNT { get; set; }
        public string MUSER { get; set; }
        public int MDATE { get; set; }
        public int MTIME { get; set; }
        public string EATTRIBUTE1 { get; set; }
        public string ISCTRL { get; set; }
    }
}
