//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_TBLONOFFDUTYMID
    {
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string LINECODE { get; set; }
        public int ONOFFDATE { get; set; }
        public int ONOFFTIME { get; set; }
        public string FLAG { get; set; }
        public decimal SERIAL { get; set; }
        public decimal NUM { get; set; }
    }
}
