//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZERPMATERIAL
    {
        public string MCODE { get; set; }
        public string MNAME { get; set; }
        public string MDESC { get; set; }
        public string MUOM { get; set; }
        public string MTYPE { get; set; }
        public string VENDORCODE { get; set; }
        public string ROHS { get; set; }
        public string FLAG { get; set; }
    }
}
