//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZERPMO
    {
        public decimal SERIAL { get; set; }
        public string MOCODE { get; set; }
        public string MOTYPE { get; set; }
        public decimal MOPLANQTY { get; set; }
        public int MOPLANSTARTDATE { get; set; }
        public int MOPLANENDDATE { get; set; }
        public string CUSITEMCODE { get; set; }
        public string ORDERNO { get; set; }
        public int ORDERSEQ { get; set; }
        public int MODOWNDATE { get; set; }
        public string MOVER { get; set; }
        public string ITEMCODE { get; set; }
        public string MOBOM { get; set; }
        public string MOREMARK { get; set; }
        public string FLAG { get; set; }
    }
}
