//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BenQGuru.eMES.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZERPINVRECEIPT
    {
        public decimal SERIAL { get; set; }
        public string RECEIPTNO { get; set; }
        public decimal RECEIPTLINE { get; set; }
        public string PURCHASENO { get; set; }
        public string PURCHASELINE { get; set; }
        public string STORAGEID { get; set; }
        public string VENDORCODE { get; set; }
        public string RECTYPE { get; set; }
        public string ITEMCODE { get; set; }
        public decimal PLANQTY { get; set; }
        public string VENDERLOTNO { get; set; }
        public string MOCODE { get; set; }
        public string MEMO { get; set; }
        public string FLAG { get; set; }
    }
}
